services:
  - type: web
    name: Gestion-Saude-backend
    runtime: python
    region: oregon
    plan: free
    workingDirectory: backend
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations usuarios && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Gestion-Saude-Base_de_Datos
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "gestion-saude-backend.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://gestion-saude.onrender.com,https://gestion-saude-backend.onrender.com"
      - key: VITE_API_URL
        value: "https://gestion-saude-backend.onrender.com/api"
      - key: DEMO_PATIENT_USERNAME
        value: "patient"
      - key: DEMO_PATIENT_PASSWORD
        value: "patient123"
