import React, { createContext, useContext, useState, useEffect } from 'react';

// Translations - Portuguese as base language
const translations = {
  // Portuguese (base)
  pt: {
    // Common
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    cancel: 'Cancelar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    view: 'Ver',
    back: 'Voltar',
    next: 'Proximo',
    previous: 'Anterior',
    yes: 'Sim',
    no: 'Nao',
    close: 'Fechar',
    confirm: 'Confirmar',
    search: 'Buscar',
    filter: 'Filtrar',
    noResults: 'Nenhum resultado encontrado',
    required: 'Obrigatorio',
    optional: 'Opcional',
    
    // Auth
    login: 'Entrar',
    logout: 'Sair',
    username: 'Usuario',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    email: 'Email',
    // Login errors
    demoNotAvailable: 'Demo nao disponivel. Por favor, use suas proprias credenciais ou configure as variaveis de ambiente DEMO_PATIENT_USERNAME e DEMO_PATIENT_PASSWORD no servidor.',
    demoNoAccess: 'A conta demo nao tem acesso de paciente. Use suas proprias credenciais.',
    serverConnectionError: 'Erro ao conectar com o servidor',
    // Perfil
    myProfile: 'Meu Perfil',
    personalInfo: 'Informacao Pessoal',
    professionalInfo: 'Informacao Profissional',
    medicalInfo: 'Informacao Medica',
    emergencyContact: 'Contato de Emergencia',
    emergencyPhone: 'Telefone de Emergencia',
    specialty: 'Especialidade',
    saveChanges: 'Salvar Alteracoes',
    saving: 'Salvando...',
    backToDashboard: 'Voltar ao Dashboard',
    // Citas
    upcomingAppointments: 'Proximas Consultas',
    confirmReservation: 'Confirmar Reserva',
    cancelAppointment: 'Cancelar consulta',
    specialtyNotSpecified: 'Especialidade nao especificada',
    noAppointmentHistory: 'Sem historico de consultas',
    completedAppointmentsAppearHere: 'As consultas concluidas aparecerão aqui',
    appointments: 'consultas',
    // Doctores
    contact: 'Contato',
    verMais: 'Ver Mais',
    noDoctorsFound: 'Nao encontrou medicos',
    withSpecialty: 'com especialidade',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Acesso Rapido de Administrador',
    managePatients: 'Gerencia pacientes, medicos, enfermeiras e consultas do sistema.',
    viewAllAppointments: 'Ver Todas as Consultas',
    // Admin Dashboard
    generalSummary: 'Resumo Geral',
    usersByRole: 'Usuarios por Funcao',
    administrators: 'Administradores',
    doctors: 'Medicos',
    patients: 'Pacientes',
    nurses: 'Enfermeiros',
    bloodType: 'Tipo Sanguineo',
    newSpecialty: 'Nova Especialidade',
    appointmentManagement: 'Gerenciamento de Consultas',
    specialtyManagement: 'Gerenciamento de Especialidades',
    scheduleManagement: 'Gerenciamento de Horarios',
    // Nursing Dashboard
    registerNew: 'Registrar Novo',
    registerSigns: 'Registrar Sinais',
    procedures: 'Procedimentos',
    pendingProcedures: 'Procedimentos Pendentes',
    registerNewProcedure: 'Registrar Novo Procedimento',
    registerProcedure: 'Registrar Procedimento',
    saveVitals: 'Salvar Sinais Vitais',
    healing: 'Curacao',
    vaccination: 'Vacinacao',
    generalNursing: 'Enfermagem Geral',
    patientsToday: 'Pacientes de Hoje',
    welcome: 'Bem-vinda',
    // Chat IA
    chatAssistantTitle: 'Assistente de Consultas',
    initialGreeting: 'Ola! 👋 Sou o assistente da Gestao-Saude.\n\nVoce esta procurando agendar uma consulta medica? Posso ajuda-lo a encontrar o medico perfeito para voce.',
    suggestion1: 'Quero agendar uma consulta',
    suggestion2: 'Ver horarios disponiveis',
    suggestion3: 'Tenho uma duvida',
    connectionTimeout: '⏱️ A conexao demorou muito. Por favor, verifique sua internet e tente novamente.',
    noAccess: '🔒 Voce nao tem acesso a esta funcao. Apenas pacientes podem usar o assistente.',
    serverError: '🔧 Ha um problema com o servidor. Por favor, tente mais tarde.',
    processingError: 'Desculpe, houve um erro ao processar sua mensagem. Por favor, tente novamente.',
    chatSuggestions: 'Sugestoes',
    writeMessage: 'Escreva sua mensagem...',
    send: 'Enviar',
    // Registro
    noAccount: 'Nao tem uma conta?',
    registerHere: 'Cadastre-se aqui',
    phone: 'Telefone',
    rememberMe: 'Lembrar-me',
    forgotPassword: 'Esqueceu a senha?',
    noAccount: 'Nao tem uma conta?',
    registerHere: 'Cadastre-se aqui',
    hasAccount: 'Ja tem uma conta?',
    loginHere: 'Entre aqui',
    createAccount: 'Criar Conta',
    register: 'Cadastrar',
    demo: 'Usar demo (admin)',
    loggingIn: 'Entrando...',
    registering: 'Cadastrando...',
    
    // Errors
    invalidCredentials: 'Usuario ou senha incorretos',
    connectionError: 'Erro ao conectar com o servidor',
    sessionExpired: 'Sessao expirada. Por favor, entre novamente.',
    unauthorized: 'Acesso nao autorizado',
    requiredField: 'Este campo e obrigatorio',
    requiredFieldIndicator: '*',
    invalidEmail: 'Email invalido',
    invalidPhone: 'Formato de telefone invalido',
    passwordTooShort: 'A senha deve ter pelo menos 4 caracteres',
    passwordMismatch: 'As senhas nao coincidem',
    usernameRequired: 'O nome de usuario e obrigatorio',
    firstNameRequired: 'O nome e obrigatorio',
    lastNameRequired: 'O sobrenome e obrigatorio',
    emailRequired: 'O email e obrigatorio',
    usernameTooShort: 'O usuario deve ter pelo menos 3 caracteres',
    usernameExists: 'O nome de usuario ja existe',
    serverError: 'Erro do servidor',
    // Registration messages
    fixFormErrors: 'Por favor corrija os erros no formulario',
    registrationSuccess: 'Cadastro realizado com sucesso! Acessando sua conta...',
    connectionTimeout: 'Tempo limite excedido ou requisicao cancelada. Verifique se o servidor esta funcionando.',
    invalidData: 'Erro nos dados enviados',
    registrationError: 'Erro no cadastro',
    cannotConnectServer: 'Nao foi possivel conectar com o servidor. Verifique se o backend esta funcionando.',
    errorConnectingServer: 'Erro ao conectar com o servidor',
    minimum3Characters: 'Minimo 3 caracteres',
    minimum4Characters: 'Minimo 4 caracteres',
    emailLabel: 'Email *',
    passwordLabel: 'Senha *',
    
    // Perfil
    loadingMedicalInfo: 'Carregando informacoes medicas...',
    loadingProfile: 'Carregando perfil...',
    loadingYourInfo: 'Carregando suas informacoes...',
    loadingProfessionalInfo: 'Carregando informacoes profissionais...',
    loadingAppointmentsHistory: 'Carregando historico de consultas...',
    medicalInfo: 'Informacoes Medicas',
    allergies: 'Alergias',
    bloodType: 'Tipo Sanguineo',
    emergencyContact: 'Contacto de Emergencia',
    emergencyPhone: 'Telefone de Emergencia',
    noAllergies: 'Sem alergias cadastradas',
    noEmergencyContact: 'Sem contacto de emergencia cadastrado',
    
    // Dashboard
    welcome: 'Bem-vindo',
    welcomeBack: 'Bem-vindo de volta',
    myProfile: 'Meu Perfil',
    personalInfo: 'Informacoes Pessoais',
    quickStats: 'Estatisticas Rapidas',
    mainMenu: 'Menu Principal',
    myAppointments: 'Minhas Consultas',
    doctors: 'Medicos',
    seeSpecialists: 'Ver especialistas disponiveis',
    editProfile: 'Editar sua informacao pessoal',
    adminPanel: 'Painel Admin',
    manageSystem: 'Gerenciar o sistema',
    notifications: 'Notificacoes',
    unreadNotifications: 'Voce tem {count} notificacao{count !== 1 ? "s" : ""} nao lida',
    clickToSee: 'Clique no sino para ver',
    seeNotifications: 'Ver notificacoes',
    
    // Admin Dashboard additional
    adminDashboardTitle: 'Painel de Administracao',
    adminDashboardSubtitle: 'Gerencie todos os aspectos do sistema',
    backToDashboard: 'Voltar ao Dashboard',
    totalUsers: 'Total de Usuarios',
    totalDoctors: 'Total de Medicos',
    totalNurses: 'Total de Enfermeiros',
    appointmentsToday: 'Consultas de Hoje',
    manageUsers: 'Gerenciar Usuarios',
    manageDoctors: 'Gerenciar Medicos',
    manageNurses: 'Gerenciar Enfermagem',
    manageAppointments: 'Gerenciar Consultas',
    patientsManagement: 'Gestao de Pacientes',
    appointments: 'Consultas',
    specialties: 'Especialidades',
    schedules: 'Horarios',
    userManagement: 'Gerenciamento de Usuarios',
    newUser: 'Novo Usuario',
    
    // Roles
    administrator: 'Administrador',
    doctor: 'Medico',
    nurse: 'Enfermagem',
    patient: 'Paciente',
    
    // Appointments
    appointments: 'Consultas',
    appointmentsManagement: 'Gestao de Consultas',
    newAppointment: 'Nova Consulta',
    bookAppointment: 'Reservar Nova Consulta',
    upcomingAppointments: 'Proximas Consultas',
    pastAppointments: 'Historico de Consultas',
    appointmentHistory: 'Historial de Consultas',
    noUpcomingAppointments: 'Voce nao tem consultas proximas',
    noPastAppointments: 'Nao ha consultas no historico',
    selectDoctor: 'Selecionar medico',
    selectPatient: 'Selecionar paciente',
    selectSpecialty: 'Selecionar especialidade',
    select: 'Selecionar',
    selectDate: 'Selecionar data',
    selectTime: 'Selecionar horario',
    availableTime: 'Horario disponivel',
    noAvailableTimes: 'Nao ha horarios disponiveis para este dia',
    loadingAvailableTimes: 'Carregando horarios disponiveis...',
    appointmentReason: 'Motivo da consulta',
    describeReason: 'Descreva o motivo da sua consulta...',
    confirmBooking: 'Confirmar Reserva',
    appointmentBooked: 'Consulta reservada com sucesso!',
    cancelAppointment: 'Cancelar Consulta',
    appointmentCancelled: 'Consulta cancelada',
    confirmCancel: 'Tem certeza que deseja cancelar esta consulta?',
    appointmentDetails: 'Detalhes da Consulta',
    date: 'Data',
    time: 'Hora',
    reason: 'Motivo',
    status: 'Status',
    
    // Appointment Status
    pending: 'Pendente',
    confirmed: 'Confirmada',
    completed: 'Concluida',
    cancelled: 'Cancelada',
    noShow: 'Nao compareceu',
    created: 'Criada',
    
    // Doctors
    ourSpecialists: 'Nossos Especialistas',
    filterBySpecialty: 'Filtrar por especialidade',
    allSpecialties: 'Todas as especialidades',
    viewAvailability: 'Ver disponibilidade',
    professionalInfo: 'Informacoes Profissionais',
    biography: 'Biografia',
    notSpecified: 'Nao especificada',
    contact: 'Contato',
    notProvided: 'Nao informado',
    officeHours: 'Horarios de Atendimento',
    noScheduleConfigured: 'Nao ha horarios configurados',
    bookAppointmentBtn: 'Reservar Consulta',
    noDoctorsFound: 'Nao foram encontrados medicos',
    noNursesFound: 'Nao foram encontradas enfermeiras',
    
    // Profile
    profile: 'Perfil',
    profileManagement: 'Gerenciamento de Perfil',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    fullName: 'Nome Completo',
    birthDate: 'Data de Nascimento',
    gender: 'Genero',
    address: 'Endereco',
    bloodType: 'Tipo Sanguineo',
    allergies: 'Alergias',
    emergencyContact: 'Contato de Emergencia',
    emergencyPhone: 'Telefone de Emergencia',
    changePassword: 'Alterar Senha',
    currentPassword: 'Senha Atual',
    newPassword: 'Nova Senha',
    confirmNewPassword: 'Confirmar Nova Senha',
    passwordChanged: 'Senha alterada com sucesso',
    currentPasswordIncorrect: 'Senha atual incorreta',
    profileUpdated: 'Perfil atualizado com sucesso',
    saveProfile: 'Salvar Perfil',
    cancelEdit: 'Cancelar Edicao',
    noHistory: 'Sem historico',
    
    // Medical Info
    medicalInfo: 'Informacoes Medicas',
    medicalHistory: 'Historico Medico',
    loadMedicalInfo: 'Carregando informacoes medicas...',
    loadProfessionalInfo: 'Carregando informacoes profissionais...',
    loadAppointmentHistory: 'Carregando historico de consultas...',
    specialty: 'Especialidade',
    otherSpecialty: 'Outra Especialidade',
    licenseNumber: 'Numero da Licenca',
    generalNursing: 'Enfermagem Geral',
    
    // Nursing Dashboard
    nursingDashboard: 'Painel de Enfermagem',
    goToNursingDashboard: 'Ir para Painel de Enfermagem',
    welcomeNurse: 'Bem-vinda',
    patientsToday: 'Pacientes de Hoje',
    procedures: 'Procedimentos',
    vitalSigns: 'Sinais Vitais',
    pendingTasks: 'Pendentes',
    patientsOfDay: 'Pacientes do Dia',
    registerNew: 'Registrar Novo',
    patientsScheduled: 'Nao ha pacientes agendados para hoje',
    registerVitals: 'Registrar Sinais',
    performDressing: 'Realizar Curativo',
    takeSample: 'Coletar Amostra',
    registerVitalSigns: 'Registrar Sinais Vitais',
    temperature: 'Temperatura (°C)',
    bloodPressure: 'Pressao Arterial',
    heartRate: 'Freq. Cardiaca (lpm)',
    respiratoryRate: 'Freq. Respiratoria',
    oxygenSaturation: 'Saturacao O2 (%)',
    glucose: 'Glicose (mg/dL)',
    weight: 'Peso (kg)',
    height: 'Altura (cm)',
    additionalNotes: 'Notas adicionais',
    observations: 'Observacoes importantes...',
    saveVitals: 'Salvar Sinais Vitais',
    vitalsRegistered: 'Sinais vitais registrados com sucesso',
    
    // Admin Dashboard
    adminDashboard: 'Painel de Administracao',
    totalUsers: 'Total de Usuarios',
    totalDoctors: 'Total de Medicos',
    totalNurses: 'Total de Enfermeiros',
    totalPatients: 'Total de Pacientes',
    appointmentsToday: 'Consultas de Hoje',
    pendingAppointments: 'Consultas Pendentes',
    totalAppointments: 'Total de Consultas',
    manageUsers: 'Gerenciar Usuarios',
    manageDoctors: 'Gerenciar Medicos',
    manageNurses: 'Gerenciar Enfermagem',
    manageAppointments: 'Gerenciar Consultas',
    manageSpecialties: 'Gerenciar Especialidades',
    manageSchedules: 'Gerenciar Horarios',
    createNew: 'Criar Novo',
    editItem: 'Editar',
    deleteItem: 'Excluir',
    viewItem: 'Ver',
    confirmDelete: 'Tem certeza de excluir este {type}? Esta acao nao pode ser desfeita.',
    itemDeleted: '{type} excluido com sucesso',
    itemCreated: '{type} criado com sucesso',
    itemUpdated: '{type} atualizado com sucesso',
    errorDeleting: 'Erro ao excluir {type}',
    errorSaving: 'Erro ao salvar {type}',

    // Admin - Additional
    patientsTab: 'Pacientes',
    patientsManagement: 'Gestao de Pacientes',
    newPatient: 'Novo Paciente',
    patientsWithAppointmentToday: 'Pacientes com consulta hoje',
    registerVitalsTitle: 'Registrar Sinais Vitais',
    managePatients: 'Gerenciar Pacientes',
    patient: 'Paciente',
    role: 'Funcao',
    userRole: 'Funcao do Usuario',
    selectRole: 'Selecionar funcao',

    // Perfil - Additional
    manageYourInfo: 'Gerencie suas informacoes pessoais e medicas',
    professionalContactInfo: 'Informacoes profissionais e de contato',
    editYourProfile: 'Edite seu perfil',
    medicalProfessional: 'Profissional da Saude',

    // Dashboard - Additional
    patientsOfDayTitle: 'Pacientes do Dia',

    // Form Labels
    name: 'Nome',
    description: 'Descricao',
    active: 'Ativo',
    inactive: 'Inativo',
    specialtyType: 'Tipo de Especialidade',
    medical: 'Medica',
    nursing: 'Enfermagem',
    technical: 'Tecnica',
    dayOfWeek: 'Dia da Semana',
    day: 'Dia',
    optional: 'opcional',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Termino',
    specialtyName: 'Nome da Especialidade',
    userData: 'Dados do Usuario',
    professionalData: 'Dados Profissionais',
    
    // Days of week
    monday: 'Segunda-feira',
    tuesday: 'Terca-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sabado',
    sunday: 'Domingo',
    
    // Footer
    version: 'Versao',
    medicalSystem: 'Sistema de gestao medica',
    
    // Table headers
    tableId: 'ID',
    tableUsername: 'Usuario',
    tableName: 'Nome',
    tableEmail: 'Email',
    tableRole: 'Funcao',
    tablePhone: 'Telefone',
    tableActions: 'Acoes',
    tableState: 'Estado',
    tableDescription: 'Descricao',
    tableType: 'Tipo',
    tableActive: 'Ativo',
    tableInactive: 'Inativo',
    tablePatient: 'Paciente',
    tableDoctor: 'Medico',
    tableDate: 'Data',
    adminDayOfWeek: 'Dia da semana',
    tableTime: 'Hora',
    tableReason: 'Motivo',
    tableStartTime: 'Hora de Inicio',
    tableEndTime: 'Hora de Termino',
    tableSpecialty: 'Especialidade',
    tableLicenseNumber: 'Numero da Licenca',
    tableBloodType: 'Tipo Sanguineo',
    tableEmergencyPhone: 'Telefone de Emergencia',
    
    // Buttons
    newAppointment: 'Nova Consulta',
    newSpecialty: 'Nova Especialidade',
    newSchedule: 'Novo Horario',
    saving: 'Salvando...',
    savingButton: 'Salvar',
    cancelButton: 'Cancelar',
    
    // Chat IA
    chatAssistant: 'Assistente de Consultas',
    typeMessage: 'Digite sua mensagem...',
    send: 'Enviar',
    loadingSuggestions: 'Carregando sugestoes...',
    connectionTimeout: 'A conexao demorou muito. Por favor, verifique sua internet e tente novamente.',
    sessionExpiredChat: 'Sessao expirada. Por favor, entre novamente.',
    accessDenied: 'Voce nao tem acesso a esta funcao. Apenas pacientes podem usar o assistente.',
    serverProblem: 'Ha um problema com o servidor. Por favor, tente mais tarde.',
    processingError: 'Desculpe, houve um erro ao processar sua mensagem. Por favor, tente novamente.',
    wantToSchedule: 'Quero agendar uma consulta',
    seeAvailableTimes: 'Ver horarios disponiveis',
    haveQuestion: 'Tenho uma duvida',
    
    // Language
    language: 'Idioma',
    changeLanguage: 'Mudar Idioma',
    portuguese: 'Portugues',
    spanish: 'Espanhol',
    english: 'Ingles',
    
    // Notifications
    'notifications.title': 'Notificacoes',
    'notifications.label': 'Notificacoes',
    'notifications.markAllRead': 'Marcar todas como lidas',
    'notifications.markAll': 'Marcar todas',
    'notifications.noNotifications': 'Nao ha notificacoes',
    'notifications.markAsRead': 'Marcar como lida',
    'notifications.delete': 'Excluir',
    'notifications.viewAll': 'Ver todas',
    
    // Login/Registro - Additional
    usernameRequiredField: 'Usuario, correo ou telefone e obrigatorio',
    passwordRequiredField: 'A senha e obrigatoria',
    enterPassword: 'Digite sua senha',
    usernameOrEmail: 'Usuario, correo ou telefone',
    patientManagement: 'Gestao de Pacientes',
    newAppointment: 'Nova Consulta',
    schedule: 'Horario',
    
    // Password strength
    passwordEmpty: 'Digite uma senha',
    passwordWeak: 'Senha fraca',
    passwordMedium: 'Senha media',
    passwordStrong: 'Senha forte',
    passwordVeryStrong: 'Senha muito forte',
    minimum3Characters: 'Minimo 3 caracteres',
    phoneFormat: 'Formato: +244 923 456 789',
    phonePlaceholder: '+244 XXX XXX XXX',
    emailPlaceholder: 'correo@ejemplo.com',
    passwordPlaceholder: '••••••••',
  },
  
  // Spanish (for browser translation compatibility)
  es: {
    loading: 'Cargando...',
    error: 'Error',
    success: 'Exito',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver',
    search: 'Buscar',
    filter: 'Filtrar',
    noResults: 'No se encontraron resultados',
    loadingData: 'Cargando datos...',
    // Login
    login: 'Iniciar Sesion',
    logout: 'Cerrar Sesion',
    username: 'Usuario',
    password: 'Contrasena',
    confirmPassword: 'Confirmar Contrasena',
    email: 'Correo Electronico',
    // Login errors
    invalidCredentials: 'Usuario o contrasena incorrectos',
    connectionError: 'Error al conectar con el servidor',
    serverError: 'Error del servidor',
    // Registro
    register: 'Registrarse',
    registrationSuccess: 'Registro realizado con exitos',
    registering: 'Registrando...',
    registrationError: 'Error en el registro',
    usernameExists: 'El nombre de usuario ya existe',
    userAlreadyRegistered: 'Este usuario ya esta registrado',
    // Form validation
    requiredField: 'Este campo es obligatorio',
    requiredFieldIndicator: '*',
    invalidEmail: 'Correo electronico invalido',
    invalidPhone: 'Formato de telefono invalido',
    passwordTooShort: 'La contrasena debe tener al menos 4 caracteres',
    passwordMismatch: 'Las contrasenas no coinciden',
    usernameRequired: 'El nombre de usuario es obligatorio',
    minimum3Characters: 'Minimo 3 caracteres',
    // Registro form
    registerHere: 'Registrese aqui',
    phone: 'Telefono',
    rememberMe: 'Recordarme',
    forgotPassword: 'Olvidaste tu contrasena?',
    noAccount: 'No tienes una cuenta?',
    phoneFormat: 'Formato: +244 923 456 789',
    phonePlaceholder: '+244 XXX XXX XXX',
    emailPlaceholder: 'correo@ejemplo.com',
    passwordPlaceholder: '••••••••',
    delete: 'Eliminar',
    edit: 'Editar',
    view: 'Ver',
    back: 'Volver',
    login: 'Iniciar Sesion',
    logout: 'Cerrar Sesion',
    username: 'Usuario',
    password: 'Contrasena',
    confirmPassword: 'Confirmar Contrasena',
    email: 'Correo Electronico',
    // Login errors
    demoNotAvailable: 'Demo no disponible. Por favor, use sus propias credenciales o configure las variables de entorno DEMO_PATIENT_USERNAME y DEMO_PATIENT_PASSWORD en el servidor.',
    demoNoAccess: 'La cuenta demo no tiene acceso de paciente. Use sus propias credenciales.',
    serverConnectionError: 'Error al conectar con el servidor',
    // Perfil
    myProfile: 'Mi Perfil',
    personalInfo: 'Informacion Personal',
    professionalInfo: 'Informacion Profesional',
    medicalInfo: 'Informacion Medica',
    emergencyContact: 'Contacto de Emergencia',
    emergencyPhone: 'Telefono de Emergencia',
    specialty: 'Especialidad',
    saveChanges: 'Guardar Cambios',
    saving: 'Guardando...',
    backToDashboard: 'Volver al Dashboard',
    // Citas
    upcomingAppointments: 'Proximas Citas',
    confirmReservation: 'Confirmar Reserva',
    cancelAppointment: 'Cancelar cita',
    specialtyNotSpecified: 'Especialidad no especificada',
    noAppointmentHistory: 'Sin historial de citas',
    completedAppointmentsAppearHere: 'Las citas completadas aparecerán aquí',
    appointments: 'citas',
    // Doctores
    contact: 'Contacto',
    verMas: 'Ver Mas',
    noDoctorsFound: 'No se encontraron doctores',
    withSpecialty: 'con especialidad',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Accesos Rapidos de Administrador',
    managePatients: 'Gestiona pacientes, doctores, enfermeras y citas del sistema.',
    viewAllAppointments: 'Ver Todas las Citas',
    // Admin Dashboard
    generalSummary: 'Resumen General',
    usersByRole: 'Usuarios por Rol',
    administrators: 'Administradores',
    doctors: 'Doctores',
    patients: 'Pacientes',
    nurses: 'Enfermeras',
    bloodType: 'Grupo Sanguineo',
    newSpecialty: 'Nueva Especialidad',
    appointmentManagement: 'Gestion de Citas',
    specialtyManagement: 'Gestion de Especialidades',
    scheduleManagement: 'Gestion de Horarios',
    // Nursing Dashboard
    registerNew: 'Registrar Nuevo',
    registerSigns: 'Registrar Signos',
    procedures: 'Procedimientos',
    pendingProcedures: 'Procedimientos Pendientes',
    registerNewProcedure: 'Registrar Nuevo Procedimiento',
    registerProcedure: 'Registrar Procedimiento',
    saveVitals: 'Guardar Signos Vitales',
    healing: 'Curacion',
    vaccination: 'Vacunacion',
    generalNursing: 'Enfermeria General',
    patientsToday: 'Pacientes de Hoy',
    welcome: 'Bienvenida',
    // Chat IA
    chatAssistantTitle: 'Asistente de Citas',
    initialGreeting: 'Hola! 👋 Soy el asistente de Gestao-Saude.\n\nEstas buscando agendar una consulta medica? Puedo ayudarte a encontrar el medico perfecto para ti.',
    suggestion1: 'Quiero agendar una consulta',
    suggestion2: 'Ver horarios disponibles',
    suggestion3: 'Tengo una duda',
    connectionTimeout: '⏱️ La conexion tardo mucho. Por favor, verifica tu internet e intenta nuevamente.',
    noAccess: '🔒 No tienes acceso a esta funcion. Solo pacientes pueden usar el asistente.',
    serverError: '🔧 Hay un problema con el servidor. Por favor, intenta mas tarde.',
    processingError: 'Disculpa, hubo un error al procesar tu mensaje. Por favor, intenta nuevamente.',
    chatSuggestions: 'Sugerencias',
    writeMessage: 'Escribe tu mensaje...',
    send: 'Enviar',
    // Registro
    noAccount: 'No tiene una cuenta?',
    registerHere: 'Registrese aqui',
    phone: 'Telefono',
    rememberMe: 'Recordarme',
    createAccount: 'Crear Cuenta',
    register: 'Registrarse',
    demo: 'Usar demo (admin)',
    loggingIn: 'Iniciando sesion...',
    registering: 'Registrando...',
    invalidCredentials: 'Usuario o contrasena incorrectos',
    connectionError: 'Error al conectar con el servidor',
    sessionExpired: 'Sesion expirada. Por favor, inicia sesion nuevamente.',
    unauthorized: 'Acceso no autorizado',
    requiredField: 'Este campo es obligatorio',
    invalidEmail: 'Correo electronico invalido',
    passwordTooShort: 'La contrasena debe tener al menos 4 caracteres',
    passwordMismatch: 'Las contrasenas no coinciden',
    usernameRequired: 'El nombre de usuario es obligatorio',
    firstNameRequired: 'El nombre es obligatorio',
    lastNameRequired: 'El apellido es obligatorio',
    emailRequired: 'El correo electronico es obligatorio',
    usernameTooShort: 'El usuario debe tener al menos 3 caracteres',
    usernameExists: 'El nombre de usuario ya existe',
    serverError: 'Error del servidor',
    // Registration messages
    fixFormErrors: 'Por favor corrija los errores en el formulario',
    registrationSuccess: 'Registro realizado con exito. Accediendo a tu cuenta...',
    connectionTimeout: 'Tiempo limite excedido o solicitud cancelada. Verifique si el servidor esta funcionando.',
    invalidData: 'Error en los datos enviados',
    registrationError: 'Error en el registro',
    cannotConnectServer: 'No se pudo conectar con el servidor. Verifique si el backend esta funcionando.',
    errorConnectingServer: 'Error al conectar con el servidor',
    minimum3Characters: 'Minimo 3 caracteres',
    minimum4Characters: 'Minimo 4 caracteres',
    emailLabel: 'Email *',
    passwordLabel: 'Contrasena *',
    
    // Perfil
    loadingMedicalInfo: 'Cargando informacion medica...',
    loadingProfile: 'Cargando perfil...',
    loadingYourInfo: 'Cargando tu informacion...',
    loadingProfessionalInfo: 'Cargando informacion profesional...',
    loadingAppointmentsHistory: 'Cargando historial de citas...',
    medicalInfo: 'Informacion Medica',
    allergies: 'Alergias',
    bloodType: 'Tipo Sanguineo',
    emergencyContact: 'Contacto de Emergencia',
    emergencyPhone: 'Telefono de Emergencia',
    noAllergies: 'Sin alergias registradas',
    noEmergencyContact: 'Sin contacto de emergencia registrado',
    
    // Dashboard
    welcome: 'Bienvenido',
    welcomeBack: 'Bienvenido de nuevo',
    myProfile: 'Mi Perfil',
    personalInfo: 'Informacion Personal',
    quickStats: 'Estadisticas Rapidas',
    mainMenu: 'Menu Principal',
    myAppointments: 'Mis Citas',
    doctors: 'Doctores',
    seeSpecialists: 'Ver especialistas disponibles',
    editProfile: 'Editar tu informacion personal',
    adminPanel: 'Panel Admin',
    manageSystem: 'Gestionar el sistema',
    notifications: 'Notificaciones',
    unreadNotifications: 'Tienes {count} notificacion{count !== 1 ? "es" : ""} sin leer',
    administrator: 'Administrador',
    doctor: 'Medico',
    nurse: 'Enfermeria',
    patient: 'Paciente',
    appointments: 'Citas',
    appointmentsManagement: 'Gestion de Citas',
    newAppointment: 'Nueva Cita',
    bookAppointment: 'Reservar Nueva Cita',
    upcomingAppointments: 'Proximas Citas',
    pastAppointments: 'Historial de Citas',
    noUpcomingAppointments: 'No tienes citas proximas',
    noPastAppointments: 'No hay citas en el historial',
    selectDoctor: 'Seleccionar doctor',
    selectPatient: 'Seleccionar paciente',
    selectSpecialty: 'Seleccionar especialidad',
    select: 'Seleccionar',
    selectDate: 'Seleccionar fecha',
    selectTime: 'Seleccionar hora',
    availableTime: 'Hora disponible',
    noAvailableTimes: 'No hay horarios disponibles para este dia',
    loadingAvailableTimes: 'Cargando horarios disponibles...',
    appointmentReason: 'Motivo de la consulta',
    describeReason: 'Describe el motivo de tu consulta...',
    confirmBooking: 'Confirmar Reserva',
    appointmentBooked: 'Cita reservada con exito!',
    cancelAppointment: 'Cancelar Cita',
    appointmentCancelled: 'Cita cancelada',
    confirmCancel: 'Estas seguro de cancelar esta cita?',
    appointmentDetails: 'Detalles de la Cita',
    date: 'Fecha',
    time: 'Hora',
    reason: 'Motivo',
    status: 'Estado',
    pending: 'Pendiente',
    confirmed: 'Confirmada',
    completed: 'Completada',
    cancelled: 'Cancelada',
    noShow: 'No asistio',
    created: 'Creada',
    ourSpecialists: 'Nuestros Especialistas',
    filterBySpecialty: 'Filtrar por especialidad',
    allSpecialties: 'Todas las especialidades',
    viewAvailability: 'Ver disponibilidad',
    professionalInfo: 'Informacion Profesional',
    biography: 'Biografia',
    notSpecified: 'No especificada',
    contact: 'Contacto',
    notProvided: 'No especificado',
    officeHours: 'Horarios de Atencion',
    noScheduleConfigured: 'No hay horarios configurados',
    bookAppointmentBtn: 'Reservar Cita',
    noDoctorsFound: 'No se encontraron doctores',
    noNursesFound: 'No se encontraron enfermeras',
    profile: 'Perfil',
    profileManagement: 'Gestion de Perfil',
    firstName: 'Nombre',
    lastName: 'Apellido',
    fullName: 'Nombre Completo',
    birthDate: 'Fecha de Nacimiento',
    gender: 'Genero',
    address: 'Direccion',
    bloodType: 'Grupo Sanguineo',
    allergies: 'Alergias',
    emergencyContact: 'Contacto de Emergencia',
    emergencyPhone: 'Telefono de Emergencia',
    changePassword: 'Cambiar Contrasena',
    currentPassword: 'Contrasena Actual',
    newPassword: 'Nueva Contrasena',
    confirmNewPassword: 'Confirmar Nueva Contrasena',
    passwordChanged: 'Contrasena cambiada con exito',
    currentPasswordIncorrect: 'Contrasena actual incorrecta',
    profileUpdated: 'Perfil actualizado con exito',
    saveProfile: 'Guardar Perfil',
    cancelEdit: 'Cancelar Edicion',
    noHistory: 'Sin historial',
    medicalInfo: 'Informacion Medica',
    medicalHistory: 'Historial Medico',
    loadMedicalInfo: 'Cargando informacion medica...',
    loadProfessionalInfo: 'Cargando informacion profesional...',
    loadAppointmentHistory: 'Cargando historial de consultas...',
    specialty: 'Especialidad',
    otherSpecialty: 'Otra Especialidad',
    licenseNumber: 'Numero de Licencia',
    generalNursing: 'Enfermeria General',
    nursingDashboard: 'Panel de Enfermeria',
    goToNursingDashboard: 'Ir a Panel de Enfermeria',
    welcomeNurse: 'Bienvenida',
    patientsToday: 'Pacientes Hoy',
    procedures: 'Procedimientos',
    vitalSigns: 'Signos Vitales',
    pendingTasks: 'Pendientes',
    patientsOfDay: 'Pacientes del Dia',
    registerNew: 'Registrar Nuevo',
    patientsScheduled: 'No hay pacientes programados para hoy',
    registerVitals: 'Registrar Signos',
    performDressing: 'Realizar Curacion',
    takeSample: 'Tomar Muestra',
    registerVitalSigns: 'Registrar Signos Vitales',
    temperature: 'Temperatura (°C)',
    bloodPressure: 'Presion Arterial',
    heartRate: 'Frec. Cardiaca (lpm)',
    respiratoryRate: 'Frec. Respiratoria',
    oxygenSaturation: 'Saturacion O2 (%)',
    glucose: 'Glucosa (mg/dL)',
    weight: 'Peso (kg)',
    height: 'Talla (cm)',
    additionalNotes: 'Notas adicionales',
    observations: 'Observaciones importantes...',
    saveVitals: 'Guardar Signos Vitales',
    vitalsRegistered: 'Signos vitales registrados correctamente',
    adminDashboard: 'Panel de Administracion',
    adminDashboardTitle: 'Panel de Administracion',
    adminDashboardSubtitle: 'Gestiona todos los aspectos del sistema',
    backToDashboard: 'Volver al Dashboard',
    totalUsers: 'Total de Usuarios',
    totalDoctors: 'Total de Doctores',
    totalNurses: 'Total de Enfermeras',
    totalPatients: 'Total de Pacientes',
    appointmentsToday: 'Citas de Hoy',
    pendingAppointments: 'Citas Pendientes',
    totalAppointments: 'Total de Citas',
    manageUsers: 'Gestionar Usuarios',
    manageDoctors: 'Gestionar Doctores',
    manageNurses: 'Gestionar Enfermeria',
    manageAppointments: 'Gestionar Citas',
    manageSpecialties: 'Gestionar Especialidades',
    manageSchedules: 'Gestionar Horarios',
    createNew: 'Crear Nuevo',
    appointments: 'Citas',
    specialties: 'Especialidades',
    schedules: 'Horarios',
    userManagement: 'Gestion de Usuarios',
    newUser: 'Nuevo Usuario',
    editItem: 'Editar',
    deleteItem: 'Eliminar',
    viewItem: 'Ver',
    confirmDelete: 'Estas seguro de eliminar este {type}? Esta accion no se puede deshacer.',
    itemDeleted: '{type} eliminado correctamente',
    itemCreated: '{type} creado correctamente',
    itemUpdated: '{type} actualizado correctamente',
    errorDeleting: 'Error al eliminar {type}',
    errorSaving: 'Error al guardar {type}',

    // Admin - Additional
    patientsTab: 'Pacientes',
    patientsManagement: 'Gestion de Pacientes',
    newPatient: 'Nuevo Paciente',
    patientsWithAppointmentToday: 'Pacientes con cita hoy',
    registerVitalsTitle: 'Registrar Signos Vitales',
    managePatients: 'Gestionar Pacientes',
    patient: 'Paciente',
    role: 'Rol',
    userRole: 'Rol del Usuario',
    selectRole: 'Seleccionar rol',

    // Perfil - Additional
    manageYourInfo: 'Gestiona tu informacion personal y medica',
    professionalContactInfo: 'Informacion profesional y de contacto',
    editYourProfile: 'Edita tu perfil',
    medicalProfessional: 'Profesional de la Salud',

    // Dashboard - Additional
    patientsOfDayTitle: 'Pacientes del Dia',

    name: 'Nombre',
    description: 'Descripcion',
    active: 'Activo',
    inactive: 'Inactivo',
    specialtyType: 'Tipo de Especialidad',
    medical: 'Medica',
    nursing: 'Enfermeria',
    technical: 'Tecnica',
    dayOfWeek: 'Dia de la Semana',
    day: 'Dia',
    optional: 'opcional',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    specialtyName: 'Nombre de la Especialidad',
    userData: 'Datos del Usuario',
    professionalData: 'Datos Profesionales',
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miercoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sabado',
    sunday: 'Domingo',
    version: 'Version',
    medicalSystem: 'Sistema de gestion medica',
    
    // Table headers
    tableId: 'ID',
    tableUsername: 'Usuario',
    tableName: 'Nombre',
    tableEmail: 'Correo Electronico',
    tableRole: 'Rol',
    tablePhone: 'Telefono',
    tableActions: 'Acciones',
    tableState: 'Estado',
    tableDescription: 'Descripcion',
    tableType: 'Tipo',
    tableActive: 'Activo',
    tableInactive: 'Inactivo',
    tablePatient: 'Paciente',
    tableDoctor: 'Doctor',
    tableDate: 'Fecha',
    adminDayOfWeek: 'Día de la semana',
    tableTime: 'Hora',
    tableReason: 'Motivo',
    tableStartTime: 'Hora de Inicio',
    tableEndTime: 'Hora de Fin',
    tableSpecialty: 'Especialidad',
    tableLicenseNumber: 'Numero de Licencia',
    tableBloodType: 'Grupo Sanguineo',
    tableEmergencyPhone: 'Telefono de Emergencia',
    
    // Buttons
    newAppointment: 'Nueva Cita',
    newSpecialty: 'Nueva Especialidad',
    newSchedule: 'Nuevo Horario',
    savingButton: 'Guardar',
    cancelButton: 'Cancelar',
    chatAssistant: 'Asistente de Citas',
    typeMessage: 'Escribe tu mensaje...',
    send: 'Enviar',
    loadingSuggestions: 'Cargando sugerencias...',
    connectionTimeout: 'La conexion tardo mucho. Por favor, verifica tu internet e intenta de nuevo.',
    sessionExpiredChat: 'Tu sesion expiro. Por favor, inicia sesion de nuevo.',
    accessDenied: 'No tienes acceso a esta funcion. Solo pacientes pueden usar el asistente.',
    serverProblem: 'Hay un problema con el servidor. Por favor, intenta mas tarde.',
    processingError: 'Lo sentimos, hubo un error al procesar tu mensaje. Por favor intenta de nuevo.',
    wantToSchedule: 'Quiero agendar una consulta',
    seeAvailableTimes: 'Ver horarios disponibles',
    haveQuestion: 'Tengo una duda',
    language: 'Idioma',
    changeLanguage: 'Cambiar Idioma',
    portuguese: 'Portugues',
    spanish: 'Espanol',
    english: 'Ingles',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.label': 'Notificaciones',
    'notifications.markAllRead': 'Marcar todas como leidas',
    'notifications.markAll': 'Marcar todas',
    'notifications.noNotifications': 'No hay notificaciones',
    'notifications.markAsRead': 'Marcar como leida',
    'notifications.delete': 'Eliminar',
    'notifications.viewAll': 'Ver todas',
    
    // Login/Registro - Additional
    usernameRequiredField: 'Usuario, correo o telefono es obligatorio',
    passwordRequiredField: 'La contrasena es obligatoria',
    enterPassword: 'Digite su contrasena',
    usernameOrEmail: 'Usuario, correo o telefono',
    patientManagement: 'Gestion de Pacientes',
    newAppointment: 'Nueva Cita',
    schedule: 'Horario',
    
    // Password strength
    passwordEmpty: 'Digite una contrasena',
    passwordWeak: 'Contrasena debil',
    passwordMedium: 'Contrasena media',
    passwordStrong: 'Contrasena fuerte',
    passwordVeryStrong: 'Contrasena muy fuerte',
  },
  
  // English
  en: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    back: 'Back',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    email: 'Email',
    // Login errors
    demoNotAvailable: 'Demo not available. Please use your own credentials or configure the environment variables DEMO_PATIENT_USERNAME and DEMO_PATIENT_PASSWORD on the server.',
    demoNoAccess: 'The demo account does not have patient access. Use your own credentials.',
    serverConnectionError: 'Error connecting to server',
    // Perfil
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    professionalInfo: 'Professional Information',
    medicalInfo: 'Medical Information',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    specialty: 'Specialty',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    backToDashboard: 'Back to Dashboard',
    // Citas
    upcomingAppointments: 'Upcoming Appointments',
    confirmReservation: 'Confirm Reservation',
    cancelAppointment: 'Cancel appointment',
    specialtyNotSpecified: 'Specialty not specified',
    noAppointmentHistory: 'No appointment history',
    completedAppointmentsAppearHere: 'Completed appointments will appear here',
    appointments: 'appointments',
    // Doctores
    contact: 'Contact',
    verMas: 'See More',
    noDoctorsFound: 'No doctors found',
    withSpecialty: 'with specialty',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Admin Quick Access',
    managePatients: 'Manage patients, doctors, nurses and system appointments.',
    viewAllAppointments: 'View All Appointments',
    // Admin Dashboard
    generalSummary: 'General Summary',
    usersByRole: 'Users by Role',
    administrators: 'Administrators',
    doctors: 'Doctors',
    patients: 'Patients',
    nurses: 'Nurses',
    bloodType: 'Blood Type',
    newSpecialty: 'New Specialty',
    appointmentManagement: 'Appointment Management',
    specialtyManagement: 'Specialty Management',
    scheduleManagement: 'Schedule Management',
    // Table headers
    tableId: 'ID',
    tableUsername: 'Username',
    tableName: 'Name',
    tableEmail: 'Email',
    tableRole: 'Role',
    tablePhone: 'Phone',
    tableActions: 'Actions',
    tableState: 'State',
    tableDescription: 'Description',
    tableType: 'Type',
    tableActive: 'Active',
    tableInactive: 'Inactive',
    tablePatient: 'Patient',
    tableDoctor: 'Doctor',
    tableDate: 'Date',
    adminDayOfWeek: 'Day of the week',
    tableTime: 'Time',
    tableReason: 'Reason',
    tableStartTime: 'Start Time',
    tableEndTime: 'End Time',
    tableSpecialty: 'Specialty',
    tableLicenseNumber: 'License Number',
    tableBloodType: 'Blood Type',
    tableEmergencyPhone: 'Emergency Phone',

    // Nursing Dashboard
    registerNew: 'Register New',
    registerSigns: 'Register Vitals',
    procedures: 'Procedures',
    pendingProcedures: 'Pending Procedures',
    registerNewProcedure: 'Register New Procedure',
    registerProcedure: 'Register Procedure',
    saveVitals: 'Save Vitals',
    healing: 'Healing',
    vaccination: 'Vaccination',
    generalNursing: 'General Nursing',
    patientsToday: 'Todays Patients',
    welcome: 'Welcome',
    // Chat IA
    chatAssistantTitle: 'Appointment Assistant',
    initialGreeting: 'Hello! 👋 I am the Gestao-Saude assistant.\n\nAre you looking to schedule a medical appointment? I can help you find the perfect doctor for you.',
    suggestion1: 'I want to schedule an appointment',
    suggestion2: 'View available schedules',
    suggestion3: 'I have a question',
    connectionTimeout: '⏱️ The connection took too long. Please check your internet and try again.',
    noAccess: '🔒 You do not have access to this function. Only patients can use the assistant.',
    serverError: '🔧 There is a problem with the server. Please try again later.',
    processingError: 'Sorry, there was an error processing your message. Please try again.',
    chatSuggestions: 'Suggestions',
    writeMessage: 'Write your message...',
    send: 'Send',
    // Registro
    noAccount: 'Dont have an account?',
    registerHere: 'Register here',
    phone: 'Phone',
    rememberMe: 'Remember me',
    createAccount: 'Create Account',
    register: 'Register',
    demo: 'Use demo (admin)',
    loggingIn: 'Logging in...',
    registering: 'Registering...',
    invalidCredentials: 'Invalid username or password',
    connectionError: 'Error connecting to server',
    sessionExpired: 'Session expired. Please login again.',
    unauthorized: 'Unauthorized access',
    requiredField: 'This field is required',
    requiredFieldIndicator: '*',
    invalidEmail: 'Invalid email',
    passwordTooShort: 'Password must be at least 4 characters',
    passwordMismatch: 'Passwords do not match',
    usernameRequired: 'Username is required',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    usernameTooShort: 'Username must be at least 3 characters',
    usernameExists: 'Username already exists',
    serverError: 'Server error',
    // Registration messages
    fixFormErrors: 'Please fix the errors in the form',
    registrationSuccess: 'Registration successful! Redirecting to your account...',
    connectionTimeout: 'Connection timeout or request cancelled. Please check if the server is running.',
    invalidData: 'Error in the submitted data',
    registrationError: 'Registration error',
    cannotConnectServer: 'Could not connect to the server. Please check if the backend is running.',
    errorConnectingServer: 'Error connecting to the server',
    minimum3Characters: 'Minimum 3 characters',
    minimum4Characters: 'Minimum 4 characters',
    emailLabel: 'Email *',
    passwordLabel: 'Password *',
    
    // Perfil
    loadingMedicalInfo: 'Loading medical information...',
    loadingProfile: 'Loading profile...',
    loadingYourInfo: 'Loading your information...',
    loadingProfessionalInfo: 'Loading professional information...',
    loadingAppointmentsHistory: 'Loading appointments history...',
    medicalInfo: 'Medical Information',
    allergies: 'Allergies',
    bloodType: 'Blood Type',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    noAllergies: 'No allergies registered',
    noEmergencyContact: 'No emergency contact registered',
    
    // Dashboard
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    quickStats: 'Quick Stats',
    mainMenu: 'Main Menu',
    myAppointments: 'My Appointments',
    doctors: 'Doctors',
    seeSpecialists: 'View available specialists',
    editProfile: 'Edit your personal information',
    adminPanel: 'Admin Panel',
    manageSystem: 'Manage the system',
    notifications: 'Notifications',
    unreadNotifications: 'You have {count} unread notification{count !== 1 ? "s" : ""}',
    administrator: 'Administrator',
    doctor: 'Doctor',
    nurse: 'Nursing',
    patient: 'Patient',
    appointments: 'Appointments',
    appointmentsManagement: 'Appointments Management',
    newAppointment: 'New Appointment',
    bookAppointment: 'Book New Appointment',
    upcomingAppointments: 'Upcoming Appointments',
    pastAppointments: 'Appointment History',
    noUpcomingAppointments: 'You have no upcoming appointments',
    noPastAppointments: 'No appointments in history',
    selectDoctor: 'Select doctor',
    selectPatient: 'Select patient',
    selectSpecialty: 'Select specialty',
    select: 'Select',
    selectDate: 'Select date',
    selectTime: 'Select time',
    availableTime: 'Available time',
    noAvailableTimes: 'No available times for this day',
    loadingAvailableTimes: 'Loading available times...',
    appointmentReason: 'Reason for consultation',
    describeReason: 'Describe the reason for your consultation...',
    confirmBooking: 'Confirm Booking',
    appointmentBooked: 'Appointment booked successfully!',
    cancelAppointment: 'Cancel Appointment',
    appointmentCancelled: 'Appointment cancelled',
    confirmCancel: 'Are you sure you want to cancel this appointment?',
    appointmentDetails: 'Appointment Details',
    date: 'Date',
    time: 'Time',
    reason: 'Reason',
    status: 'Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    noShow: 'No show',
    created: 'Created',
    ourSpecialists: 'Our Specialists',
    filterBySpecialty: 'Filter by specialty',
    allSpecialties: 'All specialties',
    viewAvailability: 'View availability',
    professionalInfo: 'Professional Information',
    biography: 'Biography',
    notSpecified: 'Not specified',
    contact: 'Contact',
    notProvided: 'Not provided',
    officeHours: 'Office Hours',
    noScheduleConfigured: 'No schedule configured',
    bookAppointmentBtn: 'Book Appointment',
    noDoctorsFound: 'No doctors found',
    noNursesFound: 'No nurses found',
    profile: 'Profile',
    profileManagement: 'Profile Management',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    birthDate: 'Birth Date',
    gender: 'Gender',
    address: 'Address',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordChanged: 'Password changed successfully',
    currentPasswordIncorrect: 'Current password is incorrect',
    profileUpdated: 'Profile updated successfully',
    saveProfile: 'Save Profile',
    cancelEdit: 'Cancel Edit',
    noHistory: 'No history',
    medicalInfo: 'Medical Information',
    medicalHistory: 'Medical History',
    loadMedicalInfo: 'Loading medical information...',
    loadProfessionalInfo: 'Loading professional information...',
    loadAppointmentHistory: 'Loading appointment history...',
    specialty: 'Specialty',
    otherSpecialty: 'Other Specialty',
    licenseNumber: 'License Number',
    generalNursing: 'General Nursing',
    nursingDashboard: 'Nursing Dashboard',
    goToNursingDashboard: 'Go to Nursing Dashboard',
    welcomeNurse: 'Welcome',
    patientsToday: 'Todays Patients',
    procedures: 'Procedures',
    vitalSigns: 'Vital Signs',
    pendingTasks: 'Pending',
    patientsOfDay: 'Patients of the Day',
    registerNew: 'Register New',
    patientsScheduled: 'No patients scheduled for today',
    registerVitals: 'Register Vitals',
    performDressing: 'Perform Dressing',
    takeSample: 'Take Sample',
    registerVitalSigns: 'Register Vital Signs',
    temperature: 'Temperature (°C)',
    bloodPressure: 'Blood Pressure',
    heartRate: 'Heart Rate (bpm)',
    respiratoryRate: 'Respiratory Rate',
    oxygenSaturation: 'O2 Saturation (%)',
    glucose: 'Glucose (mg/dL)',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    additionalNotes: 'Additional Notes',
    observations: 'Important observations...',
    saveVitals: 'Save Vital Signs',
    vitalsRegistered: 'Vital signs registered successfully',
    adminDashboard: 'Admin Dashboard',
    adminDashboardTitle: 'Administration Panel',
    adminDashboardSubtitle: 'Manage all system aspects',
    backToDashboard: 'Back to Dashboard',
    totalUsers: 'Total Users',
    totalUsers: 'Total Users',
    totalDoctors: 'Total Doctors',
    totalNurses: 'Total Nurses',
    totalPatients: 'Total Patients',
    appointmentsToday: 'Todays Appointments',
    pendingAppointments: 'Pending Appointments',
    totalAppointments: 'Total Appointments',
    manageUsers: 'Manage Users',
    manageDoctors: 'Manage Doctors',
    manageNurses: 'Manage Nursing',
    manageAppointments: 'Manage Appointments',
    manageSpecialties: 'Manage Specialties',
    manageSchedules: 'Manage Schedules',
    createNew: 'Create New',
    appointments: 'Appointments',
    specialties: 'Specialties',
    schedules: 'Schedules',
    userManagement: 'User Management',
    newUser: 'New User',
    editItem: 'Edit',
    deleteItem: 'Delete',
    viewItem: 'View',
    confirmDelete: 'Are you sure you want to delete this {type}? This action cannot be undone.',
    itemDeleted: '{type} deleted successfully',
    itemCreated: '{type} created successfully',
    itemUpdated: '{type} updated successfully',
    errorDeleting: 'Error deleting {type}',
    errorSaving: 'Error saving {type}',

    // Admin - Additional
    patientsTab: 'Patients',
    patientsManagement: 'Patient Management',
    newPatient: 'New Patient',
    patientsWithAppointmentToday: 'Patients with appointment today',
    registerVitalsTitle: 'Register Vital Signs',
    managePatients: 'Manage Patients',
    patient: 'Patient',
    role: 'Role',
    userRole: 'User Role',
    selectRole: 'Select role',

    // Perfil - Additional
    manageYourInfo: 'Manage your personal and medical information',
    professionalContactInfo: 'Professional and contact information',
    editYourProfile: 'Edit your profile',
    medicalProfessional: 'Health Professional',

    // Dashboard - Additional
    patientsOfDayTitle: 'Patients of the Day',

    name: 'Name',
    description: 'Description',
    active: 'Active',
    inactive: 'Inactive',
    specialtyType: 'Specialty Type',
    medical: 'Medical',
    nursing: 'Nursing',
    technical: 'Technical',
    dayOfWeek: 'Day of Week',
    day: 'Day',
    optional: 'optional',
    startTime: 'Start Time',
    endTime: 'End Time',
    specialtyName: 'Specialty Name',
    userData: 'User Data',
    professionalData: 'Professional Data',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    version: 'Version',
    medicalSystem: 'Medical management system',
    chatAssistant: 'Appointment Assistant',
    typeMessage: 'Type your message...',
    send: 'Send',
    loadingSuggestions: 'Loading suggestions...',
    connectionTimeout: 'The connection took too long. Please check your internet and try again.',
    sessionExpiredChat: 'Your session expired. Please login again.',
    accessDenied: 'You dont have access to this function. Only patients can use the assistant.',
    serverProblem: 'There is a problem with the server. Please try again later.',
    processingError: 'Sorry, there was an error processing your message. Please try again.',
    wantToSchedule: 'I want to schedule an appointment',
    seeAvailableTimes: 'See available times',
    haveQuestion: 'I have a question',
    language: 'Language',
    changeLanguage: 'Change Language',
    portuguese: 'Portuguese',
    spanish: 'Spanish',
    english: 'English',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.label': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAll': 'Mark all',
    'notifications.noNotifications': 'No notifications',
    'notifications.markAsRead': 'Mark as read',
    'notifications.delete': 'Delete',
    'notifications.viewAll': 'View all',
    
    // Login/Registro - Additional
    usernameRequiredField: 'Username, email or phone is required',
    passwordRequiredField: 'Password is required',
    enterPassword: 'Enter your password',
    usernameOrEmail: 'Username, email or phone',
    patientManagement: 'Patient Management',
    newAppointment: 'New Appointment',
    schedule: 'Schedule',
    enterPassword: 'Enter your password',
    usernameOrEmail: 'Username, email or phone',
    
    // Password strength
    passwordEmpty: 'Enter a password',
    passwordWeak: 'Weak password',
    passwordMedium: 'Medium password',
    passwordStrong: 'Strong password',
    passwordVeryStrong: 'Very strong password',
    minimum3Characters: 'Minimum 3 characters',
    phoneFormat: 'Format: +244 923 456 789',
    phonePlaceholder: '+244 XXX XXX XXX',
    emailPlaceholder: 'email@example.com',
    passwordPlaceholder: '••••••••',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Try to get saved language from localStorage, default to Portuguese
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  // Update the HTML lang attribute when language changes
  // This allows browser translation to work
  useEffect(() => {
    // Update localStorage
    localStorage.setItem('language', language);
    
    // Update HTML lang attribute for browser translation support
    const htmlElement = document.documentElement;
    const langMap = { pt: 'pt-BR', es: 'es', en: 'en' };
    htmlElement.lang = langMap[language] || 'pt-BR';
  }, [language]);

  // Translation function
  const t = (key, params = {}) => {
    const langTranslations = translations[language] || translations.pt;
    let text = langTranslations[key] || translations.pt[key] || key;
    
    // Replace parameters like {count} or {type}
    Object.keys(params).forEach(param => {
      text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
