import React, { createContext, useContext, useState, useEffect } from 'react';

// Translations - Portuguese as base language
const translations = {
  // Portuguese (base)
  pt: {
    // Common
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    cancel: 'Cancelar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    view: 'Ver',
    back: 'Voltar',
    next: 'Próximo',
    previous: 'Anterior',
    yes: 'Sim',
    no: 'Não',
    close: 'Fechar',
    confirm: 'Confirmar',
    search: 'Buscar',
    filter: 'Filtrar',
    noResults: 'Nenhum resultado encontrado',
    required: 'Obrigatório',
    optional: 'Opcional',
    noDataAvailable: 'Não disponível',

    // Auth
    login: 'Entrar',
    logout: 'Sair',
    username: 'Usuario',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    email: 'Email',
    // Login errors
    demoNotAvailable: 'Demo não disponível. Por favor, use suas próprias credenciais ou configure as variáveis de ambiente DEMO_PATIENT_USERNAME e DEMO_PATIENT_PASSWORD no servidor.',
    demoNoAccess: 'A conta demo não tem acesso de paciente. Use suas próprias credenciais.',
    serverConnectionError: 'Erro ao conectar com o servidor',
    // Perfil
    myProfile: 'Meu Perfil',
    personalInfo: 'Informacao Pessoal',
    professionalInfo: 'Informacao Profissional',
    medicalInfo: 'Informacao Medica',
    emergencyContact: 'Contato de Emergencia',
    emergencyPhone: 'Telefone de Emergencia',
    specialty: 'Especialidade',
    saveChanges: 'Salvar Alteracoes',
    saving: 'Salvando...',
    backToDashboard: 'Voltar ao Dashboard',
    // Citas
    upcomingAppointments: 'próximas Consultas',
    confirmReservation: 'Confirmar Reserva',
    cancelAppointment: 'Cancelar consulta',
    specialtyNotSpecified: 'Especialidade não especificada',
    noAppointmentHistory: 'Sem Histórico de consultas',
    completedAppointmentsAppearHere: 'As consultas concluidas aparecerão aqui',
    appointments: 'consultas',
    // Doctores
    contact: 'Contato',
    verMais: 'Ver Mais',
    noDoctorsFound: 'Nao encontrou Médicos',
    withSpecialty: 'com especialidade',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Acesso Rapido de Administrador',
    viewAllAppointments: 'Ver Todas as Consultas',
    // Admin Dashboard
    generalSummary: 'Resumo Geral',
    usersByRole: 'Usuarios por Funcao',
    administrators: 'Administradores',
    doctors: 'Médicos',
    patients: 'Pacientes',
    nurses: 'Enfermeiros',
    bloodType: 'Tipo Sanguíneo',
    newSpecialty: 'Nova Especialidade',
    appointmentManagement: 'Gerenciamento de Consultas',
    specialtyManagement: 'Gerenciamento de Especialidades',
    scheduleManagement: 'Gerenciamento de Horarios',
    // Nursing Dashboard
    registerNew: 'Registrar Novo',
    registerSigns: 'Registrar Sinais',
    procedures: 'Procedimentos',
    pendingProcedures: 'Procedimentos Pendentes',
    registerNewProcedure: 'Registrar Novo Procedimento',
    registerProcedure: 'Registrar Procedimento',
    saveVitals: 'Salvar Sinais Vitais',
    healing: 'Curacao',
    vaccination: 'Vacinacao',
    generalNursing: 'Enfermagem Geral',
    patientsToday: 'Pacientes de Hoje',
    welcome: 'Bem-vinda',
    // Chat IA
    chatAssistantTitle: 'Assistente de Consultas',
    scheduleAppointment: 'Agendar consulta médica',
    myAppointments: 'Minhas Consultas',
    needHelp: 'Preciso de ajuda',
    selectSpecialty: 'Selecionar especialidade',
    whatSpecialty: 'Qual especialidade você precisa?',
    selectSpecialtyOption: 'Selecione uma especialidade:',
    noDoctorsAvailable: 'Não há médicos disponíveis de',
    whichDoctor: 'Com qual médico você deseja a consulta?',
    whatDate: 'Que data funciona para você? (formato: YYYY-MM-DD)',
    today: 'Hoje',
    tomorrow: 'Amanhã',
    otherDate: 'Outra data',
    selectMonth: 'Selecione o mês:',
    selectDay: 'Selecione o dia:',
    invalidDateFormat: 'Formato de data inválido. Use YYYY-MM-DD',
    selectTime: 'Selecione um horário:',
    noAvailableSlots: 'Não há horários disponíveis para essa data.',
    appointmentSummary: 'Resumo da sua consulta',
    doctor: 'Médico',
    confirmAppointment: 'Confirmar esta consulta?',
    appointmentConfirmed: 'Consulta confirmada com sucesso!',
    appointmentBooked: 'Sua consulta com Dr. {doctorName} em {date} às {time} foi agendada.',
    bookAnother: 'Agendar outra consulta',
    viewMyAppointments: 'Ver minhas consultas',
    noAppointments: 'Você não tem consultas programadas.',
    yourAppointments: 'Suas consultas programadas:',
    errorLoadingAppointments: 'Erro ao carregar suas consultas.',
    howCanHelp: 'Em que posso ajudá-lo?',
    clinicInfo: 'Informações da clínica',
    contactSupport: 'Contatar suporte',
    backToMain: 'Voltar ao menu principal',
    missingData: 'Faltam dados. Vamos começar de novo.',
    understood: 'Entendido. Em que mais posso ajudá-lo?',
    loadingError: 'Ocorreu um erro. Por favor, tente novamente.',
    invalidOption: 'Opção inválida. Por favor, selecione uma das opções.',
    selectFromOptions: 'Por favor, selecione uma das opções disponíveis.',
    chooseSpecialty: 'Qual especialidade você precisa?',
    initialGreeting: 'Olá! 👋 Sou o assistente da Gestão-Saúde.\n\nVocê está procurando agendar uma consulta médica? Posso ajuda-lo a encontrar o Médico perfeito para você.',
    suggestion1: 'Quero agendar uma consulta',
    suggestion2: 'Ver horarios disponiveis',
    suggestion3: 'Tenho uma duvida',
    connectionTimeout: '⏱️ A conexão demorou muito. Por favor, verifique sua internet e tente novamente.',
    noAccess: '🔒 Você não tem acesso a esta função. Apenas pacientes podem usar o assistente.',
    serverError: '🔧 Há um problema com o servidor. Por favor, tente mais tarde.',
    processingError: 'Desculpe, houve um erro ao processar sua mensagem. Por favor, tente novamente.',
    chatSuggestions: 'Sugestoes',
    writeMessage: 'Escreva sua mensagem...',
    send: 'Enviar',
    // Registro
    noAccount: 'Nao tem uma conta?',
    registerHere: 'Cadastre-se aqui',
    phone: 'Telefone',
    rememberMe: 'Lembrar-me',
    forgotPassword: 'Esqueceu a senha?',
    hasAccount: 'Ja tem uma conta?',
    loginHere: 'Entre aqui',
    createAccount: 'Criar Conta',
    register: 'Cadastrar',
    demo: 'Usar demo (admin)',
    loggingIn: 'Entrando...',
    registering: 'Cadastrando...',
    namePlaceholder: 'Seu nome',
    lastNamePlaceholder: 'Seu sobrenome',
    usernamePlaceholder: 'Ex: juan.perez',
    loadDemoData: 'Carregar dados de demo',
    termsAndConditions: 'Termos e Condições',
    privacyPolicy: 'Política de Privacidade',

    // Errors
    invalidCredentials: 'Usuario ou senha incorretos',
    connectionError: 'Erro ao conectar com o servidor',
    sessionExpired: 'Sessao expirada. Por favor, entre novamente.',
    unauthorized: 'Acesso não autorizado',
    requiredField: 'Este campo é obrigatório',
    requiredFieldIndicator: '*',
    invalidEmail: 'Email inválido',
    invalidPhone: 'Formato de telefone inválido',
    passwordTooShort: 'A senha deve ter pelo menos 4 caracteres',
    passwordMismatch: 'As senhas não coincidem',
    usernameRequired: 'O nome de usuário é obrigatório',
    firstNameRequired: 'O nome é obrigatório',
    lastNameRequired: 'O sobrenome é obrigatório',
    emailRequired: 'O email é obrigatório',
    usernameTooShort: 'O usuário deve ter pelo menos 3 caracteres',
    usernameExists: 'O nome de usuario ja existe',
    // Registration messages
    fixFormErrors: 'Por favor corrija os erros no formulario',
    registrationSuccess: 'Cadastro realizado com sucesso! Acessando sua conta...',
    minimum3Characters: 'Mínimo 3 caracteres',
    minimum4Characters: 'Mínimo 4 caracteres',
    emailLabel: 'Email *',
    passwordLabel: 'Senha *',

    // Perfil - Additional fields
    loadingMedicalInfo: 'Carregando informacoes medicas...',
    loadingProfile: 'Carregando perfil...',
    loadingYourInfo: 'Carregando suas informacoes...',
    noUserDataReceived: 'Nao foram recebidos dados do usuario',
    loadingProfessionalInfo: 'Carregando informacoes profissionais...',
    loadingAppointmentsHistory: 'Carregando Histórico de consultas...',
    allergies: 'Alergias',
    noAllergies: 'Sem alergias cadastradas',
    noEmergencyContact: 'Sem contacto de emergencia cadastrado',

    // Dashboard - Additional
    welcomeBack: 'Bem-vindo de volta',
    quickStats: 'Estatisticas Rapidas',
    mainMenu: 'Menu Principal',
    seeSpecialists: 'Ver especialistas disponiveis',
    editProfile: 'Editar sua informacao pessoal',
    adminPanel: 'Painel Admin',
    manageSystem: 'Gerenciar o sistema',
    notifications: 'Notificacoes',
    unreadNotifications: 'Você tem {count} notificação{count !== 1 ? "s" : ""} não lida',
    clickToSee: 'Clique no sino para ver',
    seeNotifications: 'Ver notificacoes',
    reminders: 'Lembretes',
    managePatientsInfo: 'Gerencie pacientes, registre sinais vitais e realize procedimentos.',

    // Admin Dashboard additional
    adminDashboardTitle: 'Painel de Administracao',
    adminDashboardSubtitle: 'Gerencie todos os aspectos do sistema',
    totalUsers: 'Total de Usuarios',
    totalDoctors: 'Total de Médicos',
    totalNurses: 'Total de Enfermeiros',
    totalPatients: 'Total de Pacientes',
    appointmentsToday: 'Consultas de Hoje',
    pendingAppointments: 'Consultas Pendentes',
    totalAppointments: 'Total de Consultas',
    manageUsers: 'Gerenciar Usuarios',
    manageDoctors: 'Gerenciar Médicos',
    manageNurses: 'Gerenciar Enfermeiros',
    manageAppointments: 'Gerenciar Consultas',
    manageSpecialties: 'Gerenciar Especialidades',
    manageSchedules: 'Gerenciar Horarios',
    createNew: 'Criar Novo',
    editItem: 'Editar',
    deleteItem: 'Excluir',
    viewItem: 'Ver',
    confirmDelete: 'Tem certeza de excluir este {type}? Esta ação não pode ser desfeita.',
    itemDeleted: '{type} excluido com sucesso',
    itemCreated: '{type} criado com sucesso',
    itemUpdated: '{type} atualizado com sucesso',
    errorDeleting: 'Erro ao excluir {type}',
    errorSaving: 'Erro ao salvar {type}',
    itemActivated: '{type} ativado',
    itemDeactivated: '{type} desativado',
    errorTogglingActive: 'Erro ao alterar status',

    // Admin - Additional
    patientsTab: 'Pacientes',
    patientsManagement: 'Gestao de Pacientes',
    newPatient: 'Novo Paciente',
    patientsWithAppointmentToday: 'Pacientes com consulta hoje',
    registerVitalsTitle: 'Registrar Sinais Vitais',
    managePatients: 'Gerenciar Pacientes',
    patient: 'Paciente',
    role: 'Funcao',
    userRole: 'Funcao do Usuario',
    selectRole: 'Selecionar funcao',

    // Perfil - Additional
    manageYourInfo: 'Gerencie suas informacoes pessoais e medicas',
    professionalContactInfo: 'Informacoes profissionais e de contato',
    editYourProfile: 'Edite seu perfil',
    medicalProfessional: 'Profissional da Saude',

    // Dashboard - Additional
    patientsOfDayTitle: 'Pacientes do dia',

    // Form Labels
    name: 'Nome',
    description: 'Descricao',
    active: 'Ativo',
    inactive: 'Inativo',
    specialtyType: 'Tipo de Especialidade',
    medical: 'Medica',
    nursing: 'Enfermagem',
    technical: 'Técnica',
    dayOfWeek: 'dia da Semana',
    day: 'Dia',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Termino',
    specialtyName: 'Nome da Especialidade',
    describeSpecialty: 'Descreva a especialidade...',
    userData: 'Dados do Usuario',
    professionalData: 'Dados Profissionais',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    otherSpecialty: 'Outra Especialidade',
    selectSpecialtyHint: 'Selecione uma especialidade existente ou escreva uma nova abaixo',
    exampleSpecialtyPlaceholder: 'Ex: Medicina Tropical',
    biography: 'Biografia',
    bioPlaceholder: 'Formação, experiência, etc.',
    birthDate: 'Data de Nascimento',
    gender: 'Gênero',
    address: 'Endereço',
    allergies: 'Alergias',
    allergiesPlaceholder: 'Alergias conhecidas do paciente',
    observations: 'Observações importantes',

    // Days of week
    monday: 'Segunda-feira',
    tuesday: 'Terca-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sábado',
    sunday: 'Domingo',

    // Footer
    version: 'Versao',
    medicalSystem: 'Sistema de gestao medica',

    // Table headers
    tableId: 'ID',
    tableUsername: 'Usuario',
    tableName: 'Nome',
    tableEmail: 'Email',
    tableRole: 'Funcao',
    tablePhone: 'Telefone',
    tableActions: 'Acoes',
    tableState: 'Estado',
    tableDescription: 'Descricao',
    tableType: 'Tipo',
    tableActive: 'Ativo',
    tableInactive: 'Inativo',
    tablePatient: 'Paciente',
    tableDoctor: 'Médico',
    tableDate: 'Data',
    adminDayOfWeek: 'dia da semana',
    tableTime: 'Hora',
    tableReason: 'Motivo',
    tableStartTime: 'Hora de Inicio',
    tableEndTime: 'Hora de Termino',
    tableSpecialty: 'Especialidade',
    tableLicenseNumber: 'Número da Licenca',
    tableBloodType: 'Tipo Sanguíneo',
    tableEmergencyPhone: 'Telefone de Emergencia',

    // Days of week
    monday: 'Segunda-feira',
    tuesday: 'Terça-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sábado',
    sunday: 'Domingo',
    day: 'Dia',
    adminDayOfWeek: 'Dia da Semana',

    // Buttons
    newAppointment: 'Nova Consulta',
    newSchedule: 'Novo Horario',
    savingButton: 'Salvar',
    cancelButton: 'Cancelar',

    // Chat IA additional
    chatAssistant: 'Assistente de Consultas',
    typeMessage: 'Digite sua mensagem...',
    loadingSuggestions: 'Carregando sugestoes...',
    sessionExpiredChat: 'Sessao expirada. Por favor, entre novamente.',
    accessDenied: 'Você não tem acesso a esta função. Apenas pacientes podem usar o assistente.',
    serverProblem: 'Ha um problema com o servidor. Por favor, tente mais tarde.',
    wantToSchedule: 'Quero agendar uma consulta',
    seeAvailableTimes: 'Ver horarios disponiveis',
    haveQuestion: 'Tenho uma duvida',

    // Language
    language: 'Idioma',
    changeLanguage: 'Mudar Idioma',
    portuguese: 'Portugues',
    spanish: 'Espanhol',
    english: 'Ingles',

    // Notifications
    'notifications.title': 'Notificacoes',
    'notifications.label': 'Notificacoes',
    'notifications.markAllRead': 'Marcar todas como lidas',
    'notifications.markAll': 'Marcar todas',
    'notifications.noNotifications': 'Nao ha notificacoes',
    'notifications.markAsRead': 'Marcar como lida',
    'notifications.delete': 'Excluir',
    'notifications.viewAll': 'Ver todas',

    // Login/Registro - Additional
    usernameRequiredField: 'Usuario, correo ou telefone e obrigatorio',
    passwordRequiredField: 'A senha e obrigatoria',
    enterPassword: 'Digite sua senha',
    usernameOrEmail: 'Usuario, correo ou telefone',
    patientManagement: 'Gestao de Pacientes',
    schedule: 'Horario',

    // Password strength
    passwordEmpty: 'Digite uma senha',
    passwordWeak: 'Senha fraca',
    passwordMedium: 'Senha media',
    passwordStrong: 'Senha forte',
    passwordVeryStrong: 'Senha muito forte',
    phoneFormat: 'Formato: +244 923 456 789',
    phonePlaceholder: '+244 XXX XXX XXX',
    emailPlaceholder: 'correo@ejemplo.com',
    passwordPlaceholder: '********',
    specialties: 'Especialidades',
    schedules: 'Horarios',
    siteImages: 'Imagens do Site',
    siteImageManagement: 'Gerenciamento de Imagens',
    appointmentHistory: 'Histórico de Consultas',
    newUser: 'Novo Usuario',
    userManagement: 'Gerenciamento de Usuarios',
    administrator: 'Administrador',
    nurse: 'Enfermeiro',
    status: 'Estado',
    pending: 'Pendente',
    confirmed: 'Confirmada',
    completed: 'Completada',
    cancelled: 'Cancelada',
    noShow: 'Não compareceu',
    created: 'Criada',
    imageTitle: 'Título',
    imageDescription: 'Descrição',
    imageType: 'Tipo de Imagem',
    typeHero: 'Imagem Hero (Início)',
    typeCarousel: 'Imagem do Carrossel',
    typeGallery: 'Galeria',
    displayOrder: 'Ordem de Visualização',
    imageFile: 'Arquivo de Imagem',
    currentImage: 'Imagem atual',
    newImageSelected: 'Nova imagem selecionada',
    activeImage: 'Imagem ativa',
    imageUploaded: 'Imagem enviada com sucesso',
    imageUpdated: 'Imagem atualizada com sucesso',
    imageActivated: 'Imagem ativada',
    imageDeactivated: 'Imagem desativada',
    untitled: 'Sem título',
    cancelAppointmentOption: 'Cancelar uma cita',
    postponeAppointmentOption: 'Adiar uma cita',
    selectAppointmentToCancel: 'Selecione a cita que deseja cancelar:',
    selectAppointmentToPostpone: 'Selecione a cita que deseja adiar:',
    confirmCancellation: 'Tem certeza que deseja cancelar esta cita?',
    confirmPostponement: 'Tem certeza que deseja adiar esta cita?',
    appointmentCancelled: 'Sua cita foi cancelada com sucesso.',
    appointmentPostponed: 'Sua cita foi adiada com sucesso.',
    whichAppointmentAction: 'O que você gostaria de fazer com suas citas?',
    cancelAction: 'Cancelar cita',
    postponeAction: 'Adiar cita',
    rescheduleAppointment: 'Reagendar cita',
    selectNewDate: 'Selecione a nova data:',
    selectNewTime: 'Selecione o novo horário:',
    newDateSelected: 'Nova data selecionada',
    newTimeSelected: 'Novo horário selecionado',
    citaCancelada: 'Cita cancelada',
    citaPospuesta: 'Cita adiada',
    noCitasToCancel: 'Você não tem citas para cancelar.',
    noCitasToPostpone: 'Você não tem citas para adiar.',
    chooseAppointment: 'Escolher cita',
    backToMenu: 'Voltar ao menu',
    backToMain: 'Voltar ao menu principal',

    // Appointments
    appointments: 'consultas',
    appointmentsManagement: 'Gerenciamento de Consultas',
    newAppointment: 'Nova Consulta',
    bookAppointment: 'Reservar Nova Consulta',
    pastAppointments: 'Historico de Consultas',
    noUpcomingAppointments: 'Voce nao tem consultas proximas',
    noPastAppointments: 'Nao ha consultas no historico',
    selectDoctor: 'Selecionar medico',
    selectPatient: 'Selecionar paciente',
    typeToSearchPatient: 'Digite o nome do paciente...',
    noPatientsFound: 'Nao foram encontrados pacientes',
    select: 'Selecionar',
    selectDate: 'Selecionar data',
    availableTime: 'Horario disponivel',
    noAvailableTimes: 'Nao ha horarios disponiveis para este dia',
    loadingAvailableTimes: 'Carregando horarios disponiveis...',
    appointmentReason: 'Motivo da consulta',
    describeReason: 'Descreva o motivo da sua consulta...',
    confirmBooking: 'Confirmar Reserva',
    confirmCancel: 'Tem certeza que deseja cancelar esta consulta?',
    appointmentDetails: 'Detalhes da Consulta',
    date: 'Data',
    time: 'Hora',
    reason: 'Motivo',
    status: 'Estado'
  },

  // Spanish (for browser translation compatibility)
  es: {
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver',
    next: 'Próximo',
    previous: 'Anterior',
    yes: 'Sí',
    no: 'No',
    close: 'Cerrar',
    confirm: 'Confirmar',
    search: 'Buscar',
    filter: 'Filtrar',
    noResults: 'No se encontraron resultados',
    loadingData: 'Cargando datos...',
    noDataAvailable: 'No disponible',
    // Login
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    username: 'Usuario',
    password: 'Contrasena',
    confirmPassword: 'Confirmar Contrasena',
    email: 'Correo Electrónico',
    // Login errors
    invalidCredentials: 'Usuario o contrasena incorrectos',
    connectionError: 'Error al conectar con el servidor',
    serverError: 'Error del servidor',
    // Registro
    register: 'Registrarse',
    registrationSuccess: 'Registro realizado con éxito',
    registering: 'Registrando...',
    registrationError: 'Error en el registro',
    usernameExists: 'El nombre de usuario ya existe',
    userAlreadyRegistered: 'Este usuario ya esta registrado',
    // Form validation
    requiredField: 'Este campo es obligatorio',
    requiredFieldIndicator: '*',
    invalidEmail: 'Correo Electrónico invalido',
    invalidPhone: 'Formato de teléfono inválido',
    passwordTooShort: 'La contrasena debe tener al menos 4 caracteres',
    passwordMismatch: 'Las contrasenas no coinciden',
    usernameRequired: 'El nombre de usuario es obligatorio',
    minimum3Characters: 'Mínimo 3 caracteres',
    // Registro form
    noAccount: 'No tienes una cuenta?',
    registerHere: 'Regístrese aquí',
    phone: 'Teléfono',
    phonePlaceholder: '+244 XXX XXX XXX',
    rememberMe: 'Recordarme',
    forgotPassword: 'Olvidaste tu contrasena?',
    createAccount: 'Crear Cuenta',
    demo: 'Usar demo (admin)',
    loggingIn: 'Iniciando sesión...',
    namePlaceholder: 'Tu nombre',
    lastNamePlaceholder: 'Tu apellido',
    usernamePlaceholder: 'Ej: juan.perez',
    loadDemoData: 'Cargar datos de demo',
    termsAndConditions: 'Términos y Condiciones',
    privacyPolicy: 'Política de Privacidad',
    // Errors
    sessionExpired: 'Sesión expirada. Por favor, inicia sesión nuevamente.',
    unauthorized: 'Acceso no autorizado',
    firstNameRequired: 'El nombre es obligatorio',
    lastNameRequired: 'El apellido es obligatorio',
    emailRequired: 'El Correo Electrónico es obligatorio',
    usernameTooShort: 'El usuario debe tener al menos 3 caracteres',
    // Registration messages
    fixFormErrors: 'Por favor corrija los errores en el formulario',
    connectionTimeout: 'Tiempo límite excedido o solicitud cancelada. Verifique si el servidor esta funcionando.',
    invalidData: 'Error en los datos enviados',
    cannotConnectServer: 'No se pudo conectar con el servidor. Verifique si el backend esta funcionando.',
    errorConnectingServer: 'Error al conectar con el servidor',
    minimum4Characters: 'Mínimo 4 caracteres',
    emailLabel: 'Email *',
    passwordLabel: 'Contrasena *',

    // Perfil
    myProfile: 'Mi Perfil',
    personalInfo: 'Información Personal',
    professionalInfo: 'Información Profesional',
    medicalInfo: 'Información Médica',
    emergencyContact: 'Contacto de Emergencia',
    emergencyPhone: 'Teléfono de Emergencia',
    specialty: 'Especialidad',
    saveChanges: 'Guardar Cambios',
    saving: 'Guardando...',
    backToDashboard: 'Volver al Dashboard',
    loadingYourInfo: 'Cargando tu información...',
    noUserDataReceived: 'No fue posible cargar la información del usuario',
    // Citas
    upcomingAppointments: 'próximas Citas',
    confirmReservation: 'Confirmar Reserva',
    cancelAppointment: 'Cancelar cita',
    specialtyNotSpecified: 'Especialidad no especificada',
    noAppointmentHistory: 'Sin historial de citas',
    completedAppointmentsAppearHere: 'Las citas completadas aparecerán aquí',
    // Doctores
    contact: 'Contacto',
    verMas: 'Ver Mas',
    noDoctorsFound: 'No se encontraron doctores',
    withSpecialty: 'con especialidad',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Accesos Rápidos de Administrador',
    managePatients: 'Gestiona pacientes, doctores, enfermeras y citas del sistema.',
    viewAllAppointments: 'Ver Todas las Citas',
    // Admin Dashboard
    generalSummary: 'Resumen General',
    usersByRole: 'Usuarios por Rol',
    administrators: 'Administradores',
    doctors: 'Doctores',
    patients: 'Pacientes',
    nurses: 'Enfermeras',
    bloodType: 'Grupo Sanguíneo',
    newSpecialty: 'Nueva Especialidad',
    appointmentManagement: 'Gestión de Citas',
    specialtyManagement: 'Gestión de Especialidades',
    scheduleManagement: 'Gestión de Horarios',
    // Nursing Dashboard
    registerNew: 'Registrar Nuevo',
    registerSigns: 'Registrar Signos',
    procedures: 'Procedimientos',
    pendingProcedures: 'Procedimientos Pendientes',
    registerNewProcedure: 'Registrar Nuevo Procedimiento',
    registerProcedure: 'Registrar Procedimiento',
    saveVitals: 'Guardar Signos Vitales',
    healing: 'Curación',
    vaccination: 'Vacunación',
    generalNursing: 'Enfermería General',
    patientsToday: 'Pacientes de Hoy',
    welcome: 'Bienvenida',
    // Chat IA
    chatAssistantTitle: 'Asistente de Citas',
    scheduleAppointment: 'Agendar cita médica',
    myAppointments: 'Mis Citas',
    needHelp: 'Necesito ayuda',
    selectSpecialty: 'Seleccionar especialidad',
    whatSpecialty: '¿Qué especialidad necesitas?',
    selectSpecialtyOption: 'Selecciona una especialidad:',
    noDoctorsAvailable: 'No hay doctores disponibles de',
    whichDoctor: '¿Con qué doctor quieres la cita?',
    whatDate: '¿Qué fecha te conviene? (formato: YYYY-MM-DD)',
    today: 'Hoy',
    tomorrow: 'Mañana',
    otherDate: 'Otra fecha',
    selectMonth: 'Selecciona el mes:',
    selectDay: 'Selecciona el día:',
    invalidDateFormat: 'Formato de fecha inválido. Use YYYY-MM-DD',
    selectTime: 'Selecciona un horario:',
    noAvailableSlots: 'No hay horarios disponibles para esa fecha.',
    appointmentSummary: 'Resumen de tu cita',
    doctor: 'Doctor',
    confirmAppointment: '¿Confirmas esta cita?',
    appointmentConfirmed: '¡Cita confirmada exitosamente!',
    appointmentBooked: 'Tu cita con Dr. {doctorName} el {date} a las {time} ha sido agendada.',
    bookAnother: 'Agendar otra cita',
    viewMyAppointments: 'Ver mis citas',
    noAppointments: 'No tienes citas programadas.',
    yourAppointments: 'Tus citas programadas:',
    errorLoadingAppointments: 'Error al cargar tus citas.',
    howCanHelp: '¿En qué puedo ayudarte?',
    clinicInfo: 'Información de la clínica',
    contactSupport: 'Contactar a soporte',
    backToMain: 'Volver al menú principal',
    missingData: 'Faltan datos. Vamos a empezar de nuevo.',
    understood: 'Entendido. ¿En qué más puedo ayudarte?',
    loadingError: 'Ocurrió un error. Por favor intenta de nuevo.',
    invalidOption: 'Opción inválida. Por favor, selecciona una de las opciones.',
    selectFromOptions: 'Por favor, selecciona una de las opciones disponibles.',
    chooseSpecialty: '¿Qué especialidad necesitas?',
    initialGreeting: 'Hola! Soy el asistente de Gestao-Saude.\n\nEstas buscando agendar una consulta medica? Puedo ayudarte a encontrar el Médico perfecto para ti.',
    suggestion1: 'Quiero agendar una consulta',
    suggestion2: 'Ver horarios disponibles',
    suggestion3: 'Tengo una duda',
    processingError: 'Disculpa, hubo un error al procesar tu mensaje. Por favor, intenta nuevamente.',
    chatSuggestions: 'Sugerencias',
    writeMessage: 'Escribe tu mensaje...',

    // Chat IA - Cancel and Postpone
    cancelAppointmentOption: 'Cancelar una cita',
    postponeAppointmentOption: 'Posponer una cita',
    selectAppointmentToCancel: 'Selecciona la cita que deseas cancelar:',
    selectAppointmentToPostpone: 'Selecciona la cita que deseas posponer:',
    confirmCancellation: '¿Estás seguro de que deseas cancelar esta cita?',
    confirmPostponement: '¿Estás seguro de que deseas posponer esta cita?',
    appointmentCancelled: 'Tu cita ha sido cancelada exitosamente.',
    appointmentPostponed: 'Tu cita ha sido pospuesta exitosamente.',
    whichAppointmentAction: '¿Qué te gustaría hacer con tus citas?',
    viewAllMyCitas: 'Ver todas mis citas',
    cancelAction: 'Cancelar cita',
    postponeAction: 'Posponer cita',
    rescheduleAppointment: 'Reprogramar cita',
    selectNewDate: 'Selecciona la nueva fecha:',
    selectNewTime: 'Selecciona la nueva hora:',
    newDateSelected: 'Nueva fecha seleccionada',
    newTimeSelected: 'Nueva hora seleccionada',
    citaCancelada: 'Cita cancelada',
    citaPospuesta: 'Cita pospuesta',
    noCitasToCancel: 'No tienes citas para cancelar.',
    noCitasToPostpone: 'No tienes citas para posponer.',
    chooseAppointment: 'Elegir cita',
    backToMenu: 'Volver al men',

    // Dashboard
    welcomeBack: 'Bienvenido de nuevo',
    quickStats: 'Estadísticas Rápidas',
    mainMenu: 'Menú Principal',
    seeSpecialists: 'Ver especialistas disponibles',
    editProfile: 'Editar tu Información Personal',
    adminPanel: 'Panel Admin',
    manageSystem: 'Gestionar el sistema',
    reminders: 'Recordatorios',
    managePatientsInfo: 'Gestiona pacientes, registra signos vitales y realiza procedimientos.',
    notifications: 'notificaciones',
    unreadNotifications: 'Tienes {count} notificación{count !== 1 ? "es" : ""} sin leer',
    administrator: 'Administrador',
    nurse: 'Enfermería',
    patient: 'Paciente',

    // Appointments
    appointments: 'Citas',
    appointmentsManagement: 'Gestión de Citas',
    newAppointment: 'Nueva Cita',
    bookAppointment: 'Reservar Nueva Cita',
    pastAppointments: 'Historial de Citas',
    noUpcomingAppointments: 'No tienes citas próximas',
    noPastAppointments: 'No hay citas en el historial',
    selectDoctor: 'Seleccionar doctor',
    selectPatient: 'Seleccionar paciente',
    typeToSearchPatient: 'Digite el nombre del paciente...',
    noPatientsFound: 'No se encontraron pacientes',
    select: 'Seleccionar',
    selectDate: 'Seleccionar fecha',
    availableTime: 'Hora disponible',
    noAvailableTimes: 'No hay horarios disponibles para este dia',
    loadingAvailableTimes: 'Cargando horarios disponibles...',
    appointmentReason: 'Motivo de la consulta',
    describeReason: 'Describe el motivo de tu consulta...',
    confirmBooking: 'Confirmar Reserva',
    confirmCancel: '¿Estás seguro de cancelar esta cita?',
    appointmentDetails: 'Detalles de la Cita',
    date: 'Fecha',
    time: 'Hora',
    reason: 'Motivo',
    status: 'Estado',
    pending: 'Pendiente',
    confirmed: 'Confirmada',
    completed: 'Completada',
    cancelled: 'Cancelada',
    noShow: 'No asistió',
    created: 'Creada',

    // Doctors
    ourSpecialists: 'Nuestros Especialistas',
    filterBySpecialty: 'Filtrar por especialidad',
    allSpecialties: 'Todas las especialidades',
    viewAvailability: 'Ver disponibilidad',
    biography: 'Biografía',
    notSpecified: 'No especificada',
    notProvided: 'No especificado',
    officeHours: 'Horarios de Atención',
    noScheduleConfigured: 'No hay horarios configurados',
    bookAppointmentBtn: 'Reservar Cita',
    noNursesFound: 'No se encontraron enfermeras',

    // Admin Dashboard additional
    specialties: 'Especialidades',
    schedules: 'Horarios',
    siteImages: 'Imágenes del Sitio',
    siteImageManagement: 'Gestión de Imágenes',

    // Profile
    profile: 'Perfil',
    profileManagement: 'Gestion de Perfil',
    firstName: 'Nombre',
    lastName: 'Apellido',
    fullName: 'Nombre Completo',
    birthDate: 'Fecha de Nacimiento',
    gender: 'Género',
    address: 'Dirección',
    allergies: 'Alergias',
    allergiesPlaceholder: 'Alergias conocidas del paciente',
    changePassword: 'Cambiar Contrasena',
    currentPassword: 'Contrasena Actual',
    newPassword: 'Nueva Contrasena',
    confirmNewPassword: 'Confirmar Nueva Contrasena',
    passwordChanged: 'Contrasena cambiada con éxito',
    currentPasswordIncorrect: 'Contrasena actual incorrecta',
    profileUpdated: 'Perfil actualizado con éxito',
    saveProfile: 'Guardar Perfil',
    cancelEdit: 'Cancelar Edición',
    noHistory: 'Sin historial',

    // Medical Info
    medicalHistory: 'Historial Médico',
    loadMedicalInfo: 'Cargando Información Médica...',
    loadProfessionalInfo: 'Cargando Información Profesional...',
    loadAppointmentHistory: 'Cargando historial de consultas...',
    otherSpecialty: 'Otra Especialidad',
    selectSpecialtyHint: 'Selecciona una especialidad existente o escribe una nueva abajo',
    exampleSpecialtyPlaceholder: 'Ej: Medicina Tropical',
    biography: 'Biografía',
    bioPlaceholder: 'Formación, experiencia, etc.',
    licenseNumber: 'Número de Licencia',

    // Nursing Dashboard
    nursingDashboard: 'Panel de Enfermería',
    goToNursingDashboard: 'Ir a Panel de Enfermería',
    welcomeNurse: 'Bienvenida',
    vitalSigns: 'Signos Vitales',
    pendingTasks: 'Pendientes',
    patientsOfDay: 'Pacientes del dia',
    patientsScheduled: 'No hay pacientes programados para hoy',
    registerVitals: 'Registrar Signos',
    performDressing: 'Realizar Curación',
    takeSample: 'Tomar Muestra',
    registerVitalSigns: 'Registrar Signos Vitales',
    temperature: 'Temperatura (°C)',
    bloodPressure: 'Presión Arterial',
    heartRate: 'Frec. Cardíaca (lpm)',
    respiratoryRate: 'Frec. Respiratoria',
    oxygenSaturation: 'Saturación O2 (%)',
    glucose: 'Glucosa (mg/dL)',
    weight: 'Peso (kg)',
    height: 'Talla (cm)',
    additionalNotes: 'Notas adicionales',
    observations: 'Observaciones importantes...',
    vitalsRegistered: 'Signos vitales registrados correctamente',

    // Admin Dashboard
    adminDashboard: 'Panel de Administración',
    adminDashboardTitle: 'Panel de Administración',
    adminDashboardSubtitle: 'Gestiona todos los aspectos del sistema',
    totalUsers: 'Total de Usuarios',
    totalDoctors: 'Total de Doctores',
    totalNurses: 'Total de Enfermeras',
    totalPatients: 'Total de Pacientes',
    appointmentsToday: 'Citas de Hoy',
    pendingAppointments: 'Citas Pendientes',
    totalAppointments: 'Total de Citas',
    manageSpecialties: 'Gestionar Especialidades',
    manageSchedules: 'Gestionar Horarios',
    uploadImage: 'Subir Imagen',
    noSiteImages: 'No hay imagenesenviadas',
    uploadFirstImage: 'Subir Primera Imagen',
    imageTitle: 'Titulo',
    imageTitlePlaceholder: 'Ingrese el titulo de la imagen',
    imageDescription: 'Descripcion',
    imageDescriptionPlaceholder: 'Ingrese la descripcion de la imagen',
    imageType: 'Tipo de Imagen',
    typeHero: 'Imagen Hero (Inicio)',
    typeCarousel: 'Imagen del Carrusel',
    typeGallery: 'Galeria',
    displayOrder: 'Orden de Visualizacion',
    imageFile: 'Archivo de Imagen',
    currentImage: 'Imagen actual',
    newImageSelected: 'Nueva imagen seleccionada',
    activeImage: 'Imagen activa',
    imageUploaded: 'Imagen subida correctamente',
    imageUpdated: 'Imagen actualizada correctamente',
    imageActivated: 'Imagen activada',
    imageDeactivated: 'Imagen desactivada',
    untitled: 'Sin titulo',
    newItem: 'Nuevo',
    userManagement: 'Gestión de Usuarios',
    newUser: 'Nuevo Usuario',

    // Table headers
    tableId: 'ID',
    tableUsername: 'Usuario',
    tableName: 'Nombre',
    tableEmail: 'Correo Electrónico',
    tableRole: 'Rol',
    tablePhone: 'Teléfono',
    tableActions: 'Acciones',
    tableState: 'Estado',
    tableDescription: 'Descripción',
    tableType: 'Tipo',
    tableActive: 'Activo',
    tableInactive: 'Inactivo',
    tablePatient: 'Paciente',
    tableDoctor: 'Doctor',
    tableDate: 'Fecha',
    adminDayOfWeek: 'Día de la semana',
    tableTime: 'Hora',
    tableReason: 'Motivo',
    tableStartTime: 'Hora de Inicio',
    tableEndTime: 'Hora de Fin',
    tableSpecialty: 'Especialidad',
    tableLicenseNumber: 'Número de Licencia',
    tableBloodType: 'Grupo Sanguíneo',
    tableEmergencyPhone: 'Teléfono de Emergencia',

    // Buttons
    newSchedule: 'Nuevo Horario',
    cancelButton: 'Cancelar',

    // Chat IA additional
    chatAssistant: 'Asistente de Citas',
    typeMessage: 'Escribe tu mensaje...',
    loadingSuggestions: 'Cargando sugerencias...',
    sessionExpiredChat: 'Tu sesion expiro. Por favor, inicia sesión de nuevo.',
    accessDenied: 'No tienes acceso a esta funcion. Solo pacientes pueden usar el asistente.',
    serverProblem: 'Hay un problema con el servidor. Por favor, intenta mas tarde.',
    wantToSchedule: 'Quiero agendar una consulta',
    seeAvailableTimes: 'Ver horarios disponibles',
    haveQuestion: 'Tengo una duda',

    // Language
    language: 'Idioma',
    changeLanguage: 'Cambiar Idioma',
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sábado',
    sunday: 'Domingo',
    appointmentHistory: 'Historial de Citas',
    portuguese: 'Portugués',
    spanish: 'Español',
    english: 'Inglés',

    // Notifications
    'notifications.title': 'notificaciones',
    'notifications.label': 'notificaciones',
    'notifications.markAllRead': 'Marcar todas como leidas',
    'notifications.markAll': 'Marcar todas',
    'notifications.noNotifications': 'No hay notificaciones',
    'notifications.markAsRead': 'Marcar como leida',
    'notifications.delete': 'Eliminar',
    'notifications.viewAll': 'Ver todas',

    // Login/Registro - Additional
    usernameRequiredField: 'El nombre de usuario, correo o teléfono es obligatorio',
    passwordRequiredField: 'La contraseña es obligatoria',
    enterPasswordForm: 'Digite su contraseña',
    usernameOrEmailForm: 'Usuario, correo o Teléfono',
    patientManagement: 'Gestión de Pacientes',
    schedule: 'Horario',

    // Password strength
    passwordEmpty: 'Digite una contrasena',
    passwordWeak: 'Contrasena debil',
    passwordMedium: 'Contrasena media',
    passwordStrong: 'Contrasena fuerte',
    passwordVeryStrong: 'Contrasena muy fuerte',
  },

  // English
  en: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    back: 'Back',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    email: 'Email',
    // Login errors
    demoNotAvailable: 'Demo not available. Please use your own credentials or configure the environment variables DEMO_PATIENT_USERNAME and DEMO_PATIENT_PASSWORD on the server.',
    demoNoAccess: 'The demo account does not have patient access. Use your own credentials.',
    serverConnectionError: 'Error connecting to server',
    noDataAvailable: 'Not available',
    // Perfil
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    professionalInfo: 'Professional Information',
    medicalInfo: 'Medical Information',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    specialty: 'Specialty',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    backToDashboard: 'Back to Dashboard',
    // Citas
    upcomingAppointments: 'Upcoming Appointments',
    confirmReservation: 'Confirm Reservation',
    cancelAppointment: 'Cancel appointment',
    specialtyNotSpecified: 'Specialty not specified',
    noAppointmentHistory: 'No appointment history',
    completedAppointmentsAppearHere: 'Completed appointments will appear here',
    appointments: 'appointments',
    // Doctores
    contact: 'Contact',
    verMas: 'See More',
    noDoctorsFound: 'No doctors found',
    withSpecialty: 'with specialty',
    dr: 'Dr.',
    // Dashboard
    quickAccessAdmin: 'Admin Quick Access',
    managePatients: 'Manage patients, doctors, nurses and system appointments.',
    viewAllAppointments: 'View All Appointments',
    // Admin Dashboard
    generalSummary: 'General Summary',
    usersByRole: 'Users by Role',
    administrators: 'Administrators',
    doctors: 'Doctors',
    patients: 'Patients',
    nurses: 'Nurses',
    bloodType: 'Blood Type',
    newSpecialty: 'New Specialty',
    appointmentManagement: 'Appointment Management',
    specialtyManagement: 'Specialty Management',
    scheduleManagement: 'Schedule Management',
    // Table headers
    tableId: 'ID',
    tableUsername: 'Username',
    tableName: 'Name',
    tableEmail: 'Email',
    tableRole: 'Role',
    tablePhone: 'Phone',
    tableActions: 'Actions',
    tableState: 'State',
    tableDescription: 'Description',
    tableType: 'Type',
    tableActive: 'Active',
    tableInactive: 'Inactive',
    tablePatient: 'Patient',
    tableDoctor: 'Doctor',
    tableDate: 'Date',
    adminDayOfWeek: 'Day of the week',
    tableTime: 'Time',
    tableReason: 'Reason',
    tableStartTime: 'Start Time',
    tableEndTime: 'End Time',
    tableSpecialty: 'Specialty',
    tableLicenseNumber: 'License Number',
    tableBloodType: 'Blood Type',
    tableEmergencyPhone: 'Emergency Phone',

    // Nursing Dashboard
    registerNew: 'Register New',
    registerSigns: 'Register Vitals',
    procedures: 'Procedures',
    pendingProcedures: 'Pending Procedures',
    registerNewProcedure: 'Register New Procedure',
    registerProcedure: 'Register Procedure',
    healing: 'Healing',
    vaccination: 'Vaccination',
    generalNursing: 'General Nursing',
    // Chat IA
    chatAssistantTitle: 'Appointment Assistant',
    scheduleAppointment: 'Schedule medical appointment',
    needHelp: 'I need help',
    selectSpecialty: 'Select specialty',
    whatSpecialty: 'What specialty do you need?',
    selectSpecialtyOption: 'Select a specialty:',
    noDoctorsAvailable: 'No doctors available for',
    whichDoctor: 'Which doctor do you want the appointment with?',
    whatDate: 'What date works for you? (format: YYYY-MM-DD)',
    today: 'Today',
    tomorrow: 'Tomorrow',
    otherDate: 'Other date',
    selectMonth: 'Select the month:',
    selectDay: 'Select the day:',
    invalidDateFormat: 'Invalid date format. Use YYYY-MM-DD',
    selectTime: 'Select a time:',
    noAvailableSlots: 'No available times for that date.',
    appointmentSummary: 'Appointment Summary',
    doctor: 'Doctor',
    confirmAppointment: 'Confirm this appointment?',
    appointmentConfirmed: 'Appointment confirmed successfully!',
    appointmentBooked: 'Your appointment with Dr. {doctorName} on {date} at {time} has been scheduled.',
    bookAnother: 'Schedule another appointment',
    viewMyAppointments: 'View my appointments',
    noAppointments: 'You have no scheduled appointments.',
    yourAppointments: 'Your scheduled appointments:',
    errorLoadingAppointments: 'Error loading your appointments.',
    howCanHelp: 'How can I help you?',
    clinicInfo: 'Clinic information',
    contactSupport: 'Contact support',
    backToMain: 'Back to main menu',
    missingData: 'Missing data. Let\'s start over.',
    understood: 'Understood. How else can I help you?',
    loadingError: 'An error occurred. Please try again.',
    invalidOption: 'Invalid option. Please select one of the options.',
    selectFromOptions: 'Please select one of the available options.',
    chooseSpecialty: 'What specialty do you need?',
    initialGreeting: 'Hello! I am the Gestao-Saude assistant.\n\nAre you looking to schedule a medical appointment? I can help you find the perfect doctor for you.',
    suggestion1: 'I want to schedule an appointment',
    suggestion2: 'View available schedules',
    suggestion3: 'I have a question',
    connectionTimeout: 'The connection took too long. Please check your internet and try again.',
    noAccess: 'You do not have access to this function. Only patients can use the assistant.',
    serverError: 'There is a problem with the server. Please try again later.',
    processingError: 'Sorry, there was an error processing your message. Please try again.',
    chatSuggestions: 'Suggestions',
    writeMessage: 'Write your message...',

    // Chat IA - Cancel and Postpone
    cancelAppointmentOption: 'Cancel an appointment',
    postponeAppointmentOption: 'Postpone an appointment',
    selectAppointmentToCancel: 'Select the appointment you want to cancel:',
    selectAppointmentToPostpone: 'Select the appointment you want to postpone:',
    confirmCancellation: 'Are you sure you want to cancel this appointment?',
    confirmPostponement: 'Are you sure you want to postpone this appointment?',
    appointmentCancelled: 'Your appointment has been cancelled successfully.',
    appointmentPostponed: 'Your appointment has been postponed successfully.',
    whichAppointmentAction: 'What would you like to do with your appointments?',
    viewAllMyCitas: 'View all my appointments',
    cancelAction: 'Cancel appointment',
    postponeAction: 'Postpone appointment',
    rescheduleAppointment: 'Reschedule appointment',
    selectNewDate: 'Select the new date:',
    selectNewTime: 'Select the new time:',
    newDateSelected: 'New date selected',
    newTimeSelected: 'New time selected',
    citaCancelada: 'Appointment cancelled',
    citaPospuesta: 'Appointment postponed',
    noCitasToCancel: 'You have no appointments to cancel.',
    noCitasToPostpone: 'You have no appointments to postpone.',
    chooseAppointment: 'Choose appointment',
    backToMenu: 'Back to menu',

    // Registro
    noAccount: 'Dont have an account?',
    registerHere: 'Register here',
    phone: 'Phone',
    rememberMe: 'Remember me',
    createAccount: 'Create Account',
    register: 'Register',
    demo: 'Use demo (admin)',
    loggingIn: 'Logging in...',
    registering: 'Registering...',
    namePlaceholder: 'Your name',
    lastNamePlaceholder: 'Your last name',
    usernamePlaceholder: 'Ex: juan.perez',
    loadDemoData: 'Load demo data',
    termsAndConditions: 'Terms and Conditions',
    privacyPolicy: 'Privacy Policy',
    invalidCredentials: 'Invalid username or password',
    connectionError: 'Error connecting to server',
    sessionExpired: 'Session expired. Please login again.',
    unauthorized: 'Unauthorized access',
    requiredField: 'This field is required',
    requiredFieldIndicator: '*',
    invalidEmail: 'Invalid email',
    passwordTooShort: 'Password must be at least 4 characters',
    passwordMismatch: 'Passwords do not match',
    usernameRequired: 'Username is required',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    usernameTooShort: 'Username must be at least 3 characters',
    usernameExists: 'Username already exists',
    // Registration messages
    fixFormErrors: 'Please fix the errors in the form',
    registrationSuccess: 'Registration successful! Redirecting to your account...',
    minimum3Characters: 'Minimum 3 characters',
    minimum4Characters: 'Minimum 4 characters',
    emailLabel: 'Email *',
    passwordLabel: 'Password *',

    // Perfil
    loadingMedicalInfo: 'Loading medical information...',
    loadingProfile: 'Loading profile...',
    loadingYourInfo: 'Loading your information...',
    noUserDataReceived: 'Unable to load user data',
    loadingProfessionalInfo: 'Loading professional information...',
    loadingAppointmentsHistory: 'Loading appointments history...',
    allergies: 'Allergies',
    allergiesPlaceholder: 'Known patient allergies',
    noAllergies: 'No allergies registered',
    noEmergencyContact: 'No emergency contact registered',

    // Dashboard
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    quickStats: 'Quick Stats',
    mainMenu: 'Main Menu',
    editProfile: 'Edit your personal information',
    adminPanel: 'Admin Panel',
    manageSystem: 'Manage the system',
    reminders: 'Reminders',
    managePatientsInfo: 'Manage patients, register vital signs, and perform procedures.',
    notifications: 'Notifications',
    unreadNotifications: 'You have {count} unread notification{count !== 1 ? "s" : ""}',
    administrator: 'Administrator',
    nurse: 'Nursing',

    // Appointments continued
    selectPatient: 'Select patient',
    typeToSearchPatient: 'Type patient name...',
    noPatientsFound: 'No patients found',
    availableTime: 'Available time',
    noAvailableTimes: 'No available times for this day',
    loadingAvailableTimes: 'Loading available times...',
    appointmentReason: 'Reason for consultation',
    describeReason: 'Describe the reason for your consultation...',
    confirmBooking: 'Confirm Booking',
    confirmCancel: 'Are you sure you want to cancel this appointment?',
    appointmentDetails: 'Appointment Details',
    date: 'Date',
    time: 'Time',
    reason: 'Reason',
    status: 'Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    noShow: 'No show',
    created: 'Created',

    // Doctors continued
    ourSpecialists: 'Our Specialists',
    filterBySpecialty: 'Filter by specialty',
    allSpecialties: 'All specialties',
    viewAvailability: 'View availability',
    biography: 'Biography',
    notSpecified: 'Not specified',
    notProvided: 'Not provided',
    officeHours: 'Office Hours',
    noScheduleConfigured: 'No schedule configured',
    bookAppointmentBtn: 'Book Appointment',
    noNursesFound: 'No nurses found',

     // Admin Dashboard additional
     specialties: 'Specialties',
     schedules: 'Schedules',
     siteImages: 'Site Images',
     siteImageManagement: 'Image Management',

     // Profile
    profileManagement: 'Profile Management',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    birthDate: 'Birth Date',
    gender: 'Gender',
    address: 'Address',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordChanged: 'Password changed successfully',
    currentPasswordIncorrect: 'Current password is incorrect',
    profileUpdated: 'Profile updated successfully',
    saveProfile: 'Save Profile',
    cancelEdit: 'Cancel Edit',
    noHistory: 'No history',

    // Medical Info
    medicalHistory: 'Medical History',
    loadMedicalInfo: 'Loading medical information...',
    loadProfessionalInfo: 'Loading professional information...',
    loadAppointmentHistory: 'Loading appointment history...',
    otherSpecialty: 'Other Specialty',
    selectSpecialtyHint: 'Select an existing specialty or write a new one below',
    exampleSpecialtyPlaceholder: 'Ex: Internal Medicine',
    biography: 'Biography',
    bioPlaceholder: 'Training, experience, etc.',
    licenseNumber: 'License Number',

    // Nursing Dashboard continued
    nursingDashboard: 'Nursing Dashboard',
    goToNursingDashboard: 'Go to Nursing Dashboard',
    patientsToday: 'Todays Patients',
    patientsScheduled: 'No patients scheduled for today',
    registerVitals: 'Register Vitals',
    performDressing: 'Perform Dressing',
    takeSample: 'Take Sample',
    registerVitalSigns: 'Register Vital Signs',
    temperature: 'Temperature (°C)',
    bloodPressure: 'Blood Pressure',
    heartRate: 'Heart Rate (bpm)',
    respiratoryRate: 'Respiratory Rate',
    oxygenSaturation: 'O2 Saturation (%)',
    glucose: 'Glucose (mg/dL)',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    additionalNotes: 'Additional Notes',
    observations: 'Important observations...',
    saveVitals: 'Save Vital Signs',
    vitalsRegistered: 'Vital signs registered successfully',

    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    adminDashboardTitle: 'Administration Panel',
    adminDashboardSubtitle: 'Manage all system aspects',
    totalUsers: 'Total Users',
    totalDoctors: 'Total Doctors',
    totalNurses: 'Total Nurses',
    totalPatients: 'Total Patients',
    appointmentsToday: 'Todays Appointments',
    pendingAppointments: 'Pending Appointments',
    totalAppointments: 'Total Appointments',
    manageUsers: 'Manage Users',
    manageDoctors: 'Manage Doctors',
    manageNurses: 'Manage Nursing',
    manageAppointments: 'Manage Appointments',
    manageSpecialties: 'Manage Specialties',
    manageSchedules: 'Manage Schedules',
    createNew: 'Create New',
    uploadImage: 'Upload Image',
    noSiteImages: 'No images uploaded',
    uploadFirstImage: 'Upload First Image',
    imageTitle: 'Title',
    imageTitlePlaceholder: 'Enter image title',
    imageDescription: 'Description',
    imageDescriptionPlaceholder: 'Enter image description',
    imageType: 'Image Type',
    typeHero: 'Hero Image (Home)',
    typeCarousel: 'Carousel Image',
    typeGallery: 'Gallery',
    displayOrder: 'Display Order',
    imageFile: 'Image File',
    currentImage: 'Current image',
    newImageSelected: 'New image selected',
    activeImage: 'Active image',
    imageUploaded: 'Image uploaded successfully',
    imageUpdated: 'Image updated successfully',
    imageActivated: 'Image activated',
    imageDeactivated: 'Image deactivated',
    newItem: 'New',
    userManagement: 'User Management',
    newUser: 'New User',
    editItem: 'Edit',
    deleteItem: 'Delete',
    viewItem: 'View',
    confirmDelete: 'Are you sure you want to delete this {type}? This action cannot be undone.',
    itemDeleted: '{type} deleted successfully',
    itemCreated: '{type} created successfully',
    itemUpdated: '{type} updated successfully',
    errorDeleting: 'Error deleting {type}',
    errorSaving: 'Error saving {type}',
    itemActivated: '{type} activated',
    itemDeactivated: '{type} deactivated',
    errorTogglingActive: 'Error toggling status',

    // Admin - Additional
    patientsTab: 'Patients',
    patientsManagement: 'Patient Management',
    newPatient: 'New Patient',
    patientsWithAppointmentToday: 'Patients with appointment today',
    registerVitalsTitle: 'Register Vital Signs',
    patient: 'Patient',
    role: 'Role',
    userRole: 'User Role',
    selectRole: 'Select role',

    // Perfil - Additional
    manageYourInfo: 'Manage your personal and medical information',
    professionalContactInfo: 'Professional and contact information',
    editYourProfile: 'Edit your profile',
    medicalProfessional: 'Health Professional',

    // Dashboard - Additional
    patientsOfDayTitle: 'Patients of the Day',

    // Form Labels
    name: 'Name',
    description: 'Description',
    active: 'Active',
    inactive: 'Inactive',
    specialtyType: 'Specialty Type',
    medical: 'Medical',
    nursing: 'Nursing',
    technical: 'Technical',
    dayOfWeek: 'Day of Week',
    day: 'Day',
    optional: 'optional',
    startTime: 'Start Time',
    endTime: 'End Time',
    specialtyName: 'Specialty Name',
    phonePlaceholder: '+244 XXX XXX XXX',
    userData: 'User Data',
    professionalData: 'Professional Data',

    // Days of week
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',

    // Footer
    version: 'Version',
    medicalSystem: 'Medical management system',

    // Language
    language: 'Language',
    changeLanguage: 'Change Language',
    appointmentHistory: 'Appointment History',
    portuguese: 'Portuguese',
    spanish: 'Spanish',
    english: 'English',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.label': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAll': 'Mark all',
    'notifications.noNotifications': 'No notifications',
    'notifications.markAsRead': 'Mark as read',
    'notifications.delete': 'Delete',
    'notifications.viewAll': 'View all',

    // Login/Registro - Additional
    usernameRequiredField: 'Username, email or phone is required',
    passwordRequiredField: 'Password is required',
    enterPassword: 'Enter your password',
    usernameOrEmail: 'Username, email or phone',
    patientManagement: 'Patient Management',
    schedule: 'Schedule',

    // Password strength
    passwordEmpty: 'Enter a password',
    passwordWeak: 'Weak password',
    passwordMedium: 'Medium password',
     passwordStrong: 'Strong password',
     passwordVeryStrong: 'Very strong password',
     phoneFormat: 'Format: +244 923 456 789',
     emailPlaceholder: 'email@example.com',
     passwordPlaceholder: '********',

    // Appointments
    appointments: 'Appointments',
    appointmentsManagement: 'Appointment Management',
    newAppointment: 'New Appointment',
    bookAppointment: 'Book New Appointment',
    pastAppointments: 'Appointment History',
    noUpcomingAppointments: 'You have no upcoming appointments',
    noPastAppointments: 'No appointments in history',
    selectDoctor: 'Select doctor',
    selectPatient: 'Select patient',
    typeToSearchPatient: 'Type patient name...',
    noPatientsFound: 'No patients found',
    select: 'Select',
    selectDate: 'Select date',
    availableTime: 'Available time',
    noAvailableTimes: 'No available times for this day',
    loadingAvailableTimes: 'Loading available times...',
    appointmentReason: 'Reason for consultation',
    describeReason: 'Describe the reason for your consultation...',
    confirmBooking: 'Confirm Reservation',
    confirmCancel: 'Are you sure you want to cancel this appointment?',
    appointmentDetails: 'Appointment Details',
    date: 'Date',
    time: 'Time',
    reason: 'Reason',
    status: 'Status'
   },

  // Sitio Promocional Translations
  // Portuguese (sitio promocional)
  promo_pt: {
    // Navbar
    navInicio: 'Inicio',
    navServicos: 'Servicos',
    navSobreNos: 'Sobre Nos',
    navContacto: 'Contacto',
    navWhatsApp: 'WhatsApp',
    navLogin: 'Entrar',

    // Hero
    heroBadge: 'Atencao Medica de Qualidade',
    heroTitle: 'Cuidamos da sua saude com profissionalismo e dedicacao',
    heroSubtitle: 'Na nossa clinica encontrara uma atencao medica integral, personalizada e humana. O seu bem-estar e o da sua familia sao a nossa maxima prioridade.',
    heroLogin: 'Entrar',
    heroRegister: 'Registrar',
    heroWhatsApp: 'WhatsApp',

    // Servicios
    servicesTitle: 'Nossos Servicos',
    servicesMainTitle: 'Atenção Médica Integral',
    servicios: [
      { title: 'Consulta Medica Geral', description: 'Atencao integral para todas as idades. Diagnostico, tratamento e acompanhamento de doencas comuns.' },
      { title: 'Cardiologia', description: 'Avaliacao e tratamento de doencas do coracao e sistema cardiovascular.' },
      { title: 'Atencao de Emergencias', description: 'Servico de urgencias medicas disponivel para casos que requerem atencao imediata.' },
      { title: 'Vacinacao', description: 'Programa de vacinacao para adultos e criancas. Todas as vacinas do esquema nacional.' },
      { title: 'Análises Clínicas', description: 'Serviço de laboratório para exames de sangue, urina e outros análises diagnósticos.' },
      { title: 'Certificados Médicos', description: 'Emitimos certificados médicos para trabalho, escola, trâmites administrativos e mais.' }
    ],

    // Sobre Nosotros
    aboutTitle: 'Comprometidos com a sua Saude e Bem-estar',
    aboutDescription: 'Desde a nossa fundacao, dedicamo-nos a fornecer atencao medica de excelencia à comunidade de Benfica, Luanda. A nossa missao e fornecer atencao medica integral, humana e personalizada a cada paciente.',
    aboutDoctorDescription: 'A Dra. Belkis Morejon Acosta lidera a nossa equipe com uma visao clara: oferecer atencao medica acessivel, de qualidade e centrada no paciente. A nossa equipe esta comprometida com o seu bem-estar integral.',
    aboutFeatures: [
      { text: 'Profissionais altamente qualificados' },
      { text: 'Atencao personalizada e sem pressas' },
      { text: 'Cuidado humano e empatico' },
      { text: 'Padroes de qualidade certificados' }
    ],
    statsYears: 'Anos',
    statsPatients: 'Pacientes',
    statsSatisfaction: 'Satisfacao',
    statsEmergency: '24/7',

    // Testimonios
    testimonialsTitle: 'O que nossos pacientes dizem',
    testimonials: [
      { name: 'Maria Garcia', text: 'Excelente atencao. A Dra. Belkis e muito profissional e dedicada. Sempre me sinto bem atendida em cada consulta.' },
      { name: 'Joao Pedro', text: 'Muito bom servico. O consultorio esta bem equipado e o pessoal e muito amavel. Recomendado.' },
      { name: 'Ana Cristina', text: 'A Dra. Morejon e uma excelente medica. Ajudou-me muito com o meu tratamento. Obrigado pela sua dedicacao.' }
    ],

    // Contacto
    contactTitle: 'Contacte-nos',
    contactSubtitle: 'Estamos prontos para atender. Pode visitar-nos, ligar-nos ou escrever-nos.',
    contactAddress: 'Benfica, Luanda, Angola',
    contactPhone: '+244 923 456 789',
    contactEmail: 'contacto@drabelkismorejon.co.ao',
    contactHours: 'Segunda a Sexta: 8:00 - 18:00',

    // CTA
    ctaTitle: 'Pronto para cuidar da sua saúde?',
    ctaSubtitle: 'Registre-se na nossa plataforma para gerir as suas consultas e acessar o seu histórico médico.',
    ctaLogin: 'Entrar',
    ctaRegister: 'Registrar',

    // Footer
    footerDescription: 'Consultório médico da Dra. Belkis Morejon Acosta. Comprometidos com a sua saúde e bem-estar em Benfica, Luanda.',
    footerQuickLinks: { inicio: 'Inicio', servicos: 'Servicos', sobreNos: 'Sobre Nos', contacto: 'Contacto' },
    footerServices: { consulta: 'Consulta Médica', cardiologia: 'Cardiologia', emergencias: 'Emergências', vacinacao: 'Vacinação', analise: 'Análises Clínicas' },
    footerCopyright: `© ${new Date().getFullYear()} Todos os direitos reservados.`,
    footerDesigned: 'Designed with care for your health',
    autoMode: 'Modo automático (segue preferência do sistema)',
    toggleTheme: 'Alternar para modo escuro',
    changeLanguage: 'Clique para mudar o idioma',
    errorLoading: 'Erro ao carregar',
    connectionError: 'Erro de conexão'
  },

  // Spanish (sitio promocional)
  promo_es: {
    // Navbar
    navInicio: 'Inicio',
    navServicos: 'Servicios',
    navSobreNos: 'Sobre Nosotros',
    navContacto: 'Contacto',
    navWhatsApp: 'WhatsApp',
    navLogin: 'Iniciar Sesión',

    // Hero
    heroBadge: 'Atención Médica de Calidad',
    heroTitle: 'Cuidamos de tu salud con profesionalismo y dedicación',
    heroSubtitle: 'En nuestra clínica encontrarás una atención médica integral, personalizada y humana. Tu bienestar y el de tu familia son nuestra máxima prioridad.',
    heroLogin: 'Iniciar Sesión',
    heroRegister: 'Registrarse',
    heroWhatsApp: 'WhatsApp',

    // Servicios
    servicesTitle: 'Nuestros Servicios',
    servicesMainTitle: 'Atención Médica Integral',
    servicios: [
      { title: 'Consulta Médica General', description: 'Atención integral para todas las edades. Diagnóstico, tratamiento y seguimiento de enfermedades comunes.' },
      { title: 'Cardiología', description: 'Evaluación y tratamiento de enfermedades del corazón y sistema cardiovascular.' },
      { title: 'Atención de Emergencias', description: 'Servicio de urgencias médicas disponible para casos que requieren atención inmediata.' },
      { title: 'Vacunación', description: 'Programa de vacunación para adultos y niños. Todas las vacunas del esquema nacional.' },
      { title: 'Análisis Clínicos', description: 'Servicio de laboratorio para exámenes de sangre, orina y otros análisis diagnósticos.' },
      { title: 'Certificados Médicos', description: 'Emitimos certificados médicos para trabajo, escuela, trámites administrativos y más.' }
    ],

    // Sobre Nosotros
    aboutTitle: 'Comprometidos con tu Salud y Bienestar',
    aboutDescription: 'Desde nuestra fundación, nos hemos dedicado a proporcionar atención médica de excelencia a la comunidad de Benfica, Luanda. Nuestra misión es proporcionar atención médica integral, humana y personalizada a cada paciente.',
    aboutDoctorDescription: 'La Dra. Belkis Morejón Acosta lidera nuestro equipo con una visión clara: ofrecer atención médica accesible, de calidad y centrada en el paciente. Nuestro equipo está comprometido con tu bienestar integral.',
    aboutFeatures: [
      { text: 'Profesionales altamente cualificados' },
      { text: 'Atención personalizada y sin prisas' },
      { text: 'Cuidado humano y empático' },
      { text: 'Estándares de calidad certificados' }
    ],
    statsYears: 'Años',
    statsPatients: 'Pacientes',
    statsSatisfaction: 'Satisfacción',
    statsEmergency: '24/7',

    // Testimonios
    testimonialsTitle: 'Lo que dicen nuestros pacientes',
    testimonials: [
      { name: 'Maria Garcia', text: 'Excelente atención. La Dra. Belkis es muy profesional y dedicada. Siempre me siento bien atendida en cada consulta.' },
      { name: 'Joao Pedro', text: 'Muy buen servicio. El consultorio está bien equipado y el personal es muy amable. Recomendado.' },
      { name: 'Ana Cristina', text: 'La Dra. Morejón es una excelente médica. Me ha ayudado mucho con mi tratamiento. Gracias por su dedicación.' }
    ],

    // Contacto
    contactTitle: 'Contáctenos',
    contactSubtitle: 'Estamos listos para atenderte. Puedes visitarnos, llamarnos o escribirnos.',
    contactAddress: 'Benfica, Luanda, Angola',
    contactPhone: '+244 923 456 789',
    contactEmail: 'contacto@drabelkismorejon.co.ao',
    contactHours: 'Lunes a Viernes: 8:00 - 18:00',

    // CTA
    ctaTitle: '¿Listo para cuidar tu salud?',
    ctaSubtitle: 'Regístrate en nuestra plataforma para gestionar tus citas y acceder a tu historial médico.',
    ctaLogin: 'Iniciar Sesión',
    ctaRegister: 'Registrarse',

    // Footer
    footerDescription: 'Consultorio médico de la Dra. Belkis Morejón Acosta. Comprometidos con tu salud y bienestar en Benfica, Luanda.',
    footerQuickLinks: { inicio: 'Inicio', servicos: 'Servicios', sobreNos: 'Sobre Nosotros', contacto: 'Contacto' },
    footerServices: { consulta: 'Consulta Médica', cardiologia: 'Cardiología', emergencias: 'Emergencias', vacinacion: 'Vacunación', analise: 'Análisis Clínicos' },
    footerCopyright: `© ${new Date().getFullYear()} Todos los derechos reservados.`,
    footerDesigned: 'Designed with care for your health',
    autoMode: 'Modo automático (sigue preferencia del sistema)',
    toggleTheme: 'Cambiar a modo oscuro',
    changeLanguage: 'Haz clic para cambiar el idioma',
    errorLoading: 'Error al cargar',
    connectionError: 'Error de conexión'
  },

  // English (sitio promocional)
  promo_en: {
    // Navbar
    navInicio: 'Home',
    navServicos: 'Services',
    navSobreNos: 'About Us',
    navContacto: 'Contact',
    navWhatsApp: 'WhatsApp',
    navLogin: 'Login',

    // Hero
    heroBadge: 'Quality Medical Care',
    heroTitle: 'We take care of your health with professionalism and dedication',
    heroSubtitle: 'At our clinic you will find comprehensive, personalized and human medical care. Your well-being and that of your family are our top priority.',
    heroLogin: 'Login',
    heroRegister: 'Register',
    heroWhatsApp: 'WhatsApp',

    // Servicios
    servicesTitle: 'Our Services',
    servicesMainTitle: 'Comprehensive Medical Care',
    servicios: [
      { title: 'General Medical Consultation', description: 'Comprehensive care for all ages. Diagnosis, treatment and follow-up of common diseases.' },
      { title: 'Cardiology', description: 'Evaluation and treatment of heart and cardiovascular system diseases.' },
      { title: 'Emergency Care', description: 'Emergency medical service available for cases requiring immediate attention.' },
      { title: 'Vaccination', description: 'Vaccination program for adults and children. All vaccines from the national schedule.' },
      { title: 'Clinical Analysis', description: 'Laboratory service for blood, urine and other diagnostic tests.' },
      { title: 'Medical Certificates', description: 'We issue medical certificates for work, school, administrative procedures and more.' }
    ],

    // Sobre Nosotros
    aboutTitle: 'Committed to your Health and Well-being',
    aboutDescription: 'Since our foundation, we have been dedicated to providing excellent medical care to the community of Benfica, Luanda. Our mission is to provide comprehensive, human and personalized medical care to each patient.',
    aboutDoctorDescription: 'Dr. Belkis Morejon Acosta leads our team with a clear vision: to offer accessible, quality medical care focused on the patient. Our team is committed to your integral well-being.',
    aboutFeatures: [
      { text: 'Highly qualified professionals' },
      { text: 'Personalized care without rushing' },
      { text: 'Human and empathetic care' },
      { text: 'Certified quality standards' }
    ],
    statsYears: 'Years',
    statsPatients: 'Patients',
    statsSatisfaction: 'Satisfaction',
    statsEmergency: '24/7',

    // Testimonios
    testimonialsTitle: 'What our patients say',
    testimonials: [
      { name: 'Maria Garcia', text: 'Excellent care. Dr. Belkis is very professional and dedicated. I always feel well attended at each consultation.' },
      { name: 'Joao Pedro', text: 'Very good service. The clinic is well equipped and the staff is very friendly. Recommended.' },
      { name: 'Ana Cristina', text: 'Dr. Morejon is an excellent doctor. She has helped me a lot with my treatment. Thank you for your dedication.' }
    ],

    // Contacto
    contactTitle: 'Contact Us',
    contactSubtitle: 'We are ready to assist you. You can visit us, call us or write to us.',
    contactAddress: 'Benfica, Luanda, Angola',
    contactPhone: '+244 923 456 789',
    contactEmail: 'contacto@drabelkismorejon.co.ao',
    contactHours: 'Monday to Friday: 8:00 - 18:00',

    // CTA
    ctaTitle: 'Ready to take care of your health?',
    ctaSubtitle: 'Register on our platform to manage your appointments and access your medical history.',
    ctaLogin: 'Login',
    ctaRegister: 'Register',

    // Footer
    footerDescription: 'Medical office of Dr. Belkis Morejon Acosta. Committed to your health and well-being in Benfica, Luanda.',
    footerQuickLinks: { inicio: 'Home', servicos: 'Services', sobreNos: 'About Us', contacto: 'Contact' },
    footerServices: { consulta: 'Medical Consultation', cardiologia: 'Cardiology', emergencias: 'Emergencies', vacinacao: 'Vaccination', analise: 'Clinical Analysis' },
    footerCopyright: `© ${new Date().getFullYear()} All rights reserved.`,
    footerDesigned: 'Designed with care for your health',
    autoMode: 'Automatic mode (follows system preference)',
    toggleTheme: 'Switch to dark mode',
    changeLanguage: 'Click to change language',
    errorLoading: 'Error loading',
    connectionError: 'Connection error'
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Try to get saved language from localStorage, default to Portuguese
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  // Update the HTML lang attribute when language changes
  // This allows browser translation to work
  useEffect(() => {
    // Update localStorage
    localStorage.setItem('language', language);
    
    // Update HTML lang attribute for browser translation support
    const htmlElement = document.documentElement;
    const langMap = { pt: 'pt-BR', es: 'es', en: 'en' };
    htmlElement.lang = langMap[language] || 'pt-BR';
  }, [language]);

  // Translation function
  const t = (key, params = {}) => {
    const langTranslations = translations[language] || translations.pt;
    let text = langTranslations[key] || translations.pt[key] || key;
    
    // Replace parameters like {count} or {type}
    Object.keys(params).forEach(param => {
      text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
    });
    
    return text;
  };

  // Promotional site translation function
  const tPromo = (key, params = {}) => {
    const promoLang = `promo_${language}`;
    const langTranslations = translations[promoLang] || translations.promo_pt;
    let text = langTranslations[key] || translations.promo_pt[key] || key;
    
    // Replace parameters like {count} or {type}
    Object.keys(params).forEach(param => {
      text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tPromo, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
