# Generated by Django 6.0.2 on 2026-02-28 05:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_especialidad', models.CharField(choices=[('medica', 'Especialidad Médica'), ('enfermeria', 'Especialidad de Enfermería'), ('ambas', 'Ambos tipos')], default='medica', max_length=20, verbose_name='Tipo de especialidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Médico'), ('nurse', 'Enfermería'), ('patient', 'Paciente')], default='patient', max_length=10, verbose_name='Rol del usuario')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuarios_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otra_especialidad', models.CharField(blank=True, help_text='Si no encuentras tu especialidad, escríbela aquí', max_length=100, verbose_name='Otra especialidad')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía profesional')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
                ('especialidad', models.ForeignKey(help_text='Selecciona la especialidad principal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidad', verbose_name='Especialidad médica')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otra_especialidad', models.CharField(blank=True, help_text='Si no encuentras tu especialidad, escríbela aquí', max_length=100, verbose_name='Otra especialidad')),
                ('numero_licencia', models.CharField(blank=True, max_length=50, verbose_name='Número de licencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_enfermera', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
                ('especialidad', models.ForeignKey(blank=True, help_text='Selecciona la especialidad (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidad', verbose_name='Especialidad de enfermería')),
            ],
            options={
                'verbose_name': 'Enfermera',
                'verbose_name_plural': 'Enfermeras',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguíneo')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Nombre contacto de emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Horario activo')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['doctor', 'dia_semana', 'hora_inicio'],
                'unique_together': {('doctor', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora', models.TimeField(verbose_name='Hora de la cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=15, verbose_name='Estado de la cita')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas internas (solo staff)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('doctor', 'fecha', 'hora')},
            },
        ),
    ]
