# Generated by Django 6.0.2 on 2026-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='sitio/', verbose_name='Archivo de imagen')),
                ('tipo', models.CharField(choices=[('hero', 'Imagen Hero (Inicio)'), ('carousel', ' imagen del Carrusel'), ('galeria', 'Galería')], default='carousel', max_length=20)),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen del Sitio',
                'verbose_name_plural': 'Imágenes del Sitio',
                'ordering': ['tipo', 'orden', '-fecha_creacion'],
            },
        ),
    ]
