# Generated by Django 6.0.2 on 2026-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sitio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermera',
            name='biografia',
            field=models.TextField(blank=True, verbose_name='Biografía profesional'),
        ),
        migrations.AlterField(
            model_name='sitioimagen',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='sitioimagen',
            name='tipo',
            field=models.CharField(choices=[('hero', 'Imagen Hero (Inicio)'), ('carousel', 'Carrusel'), ('galeria', 'Galería')], default='carousel', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitioimagen',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Título'),
        ),
    ]
